### ISSUE TITLE
vue 2 使用出现  not found in 'vue-demi'

### ISSUE THREAD

**Issue by lework** [Shimada666/v-code-diff#1]
错误信息如下：

```
 warning  in ./node_modules/v-code-diff/dist/v-code-diff.esm.js

"export 'withDirectives' (imported as 'i') was not found in 'vue-demi'
```

**Comment by Shimada666** [comment]
这个版本(0.3.0)为了提高性能，使用了自定义指令，vue2没有对应的函数导致的警告，忽略即可，我正在找解决警告的办法，也可以回退上个版本，上个版本没警告

**Comment by lework** [comment]
嗯嗯，感谢回复。

在两个文本行数不一致的情况下，会出现倾斜的情况，变动行没有对齐。如下效果


![image](https://user-images.githubusercontent.com/17396943/128295501-a95a9a65-9d86-4fa4-8170-2fe90724244a.png)

**Comment by Shimada666** [comment]
可否发一下两边 diff 的内容？我看一下

**Comment by lework** [comment]
文本，https://paste.ubuntu.com/p/rnhSMJnDq3/

**Comment by lework** [comment]
https://github.com/ddchef/vue-code-diff/issues/58 看下这个，修改下样式好些就行了。

**Comment by Shimada666** [comment]
确实，我在 chrome 出现了类似的样式问题，我尝试修复下

**Comment by lework** [comment]
@Shimada666 大佬，这个有办法解决么？

**Comment by Shimada666** [comment]
请稍等，我看下，上周处理别的事了。应该是可以解决

**Comment by lework** [comment]
嗯嗯，我又来催大佬了。

**Comment by Shimada666** [comment]
马上，马上，这周一定弄完

**Comment by Shimada666** [comment]
> 嗯嗯，我又来催大佬了。

css 问题已修复，警告问题我再看看有没有办法。目前已经可以正常使用了，0.3.1 版本

**Comment by lework** [comment]
感谢大佬。我这边也更新了。

**Comment by Shimada666** [comment]
> 感谢大佬。我这边也更新了。

好的，关于警告问题，有办法解决的时候我再通知一下你

**Comment by Shimada666** [comment]
> 错误信息如下：
> 
> ```
>  warning  in ./node_modules/v-code-diff/dist/v-code-diff.esm.js
> 
> "export 'withDirectives' (imported as 'i') was not found in 'vue-demi'
> ```

0.3.2 版本修复了这个警告，可以试下
