### ISSUE TITLE
Uncaught TypeError: highlight_js__WEBPACK_IMPORTED_MODULE_3___default.a.highlightElement is not a function

### ISSUE THREAD

**Issue by zhoufanglu** [Shimada666/v-code-diff#10]
![image](https://user-images.githubusercontent.com/24451091/134797505-90cedf86-d12c-4fab-93a1-779899a2c36d.png)

## vue2里面使用
```html
          <code-diff
              :old-string="oldString"
              :new-string="newString"
              output-format="side-by-side"
              :context="10"
          >
          </code-diff>
```

**Comment by Shimada666** [comment]
重启一下你的服务试试

**Comment by zhoufanglu** [comment]
> 重启一下你的服务试试

试过了

**Comment by Shimada666** [comment]
> > 重启一下你的服务试试
> 
> 试过了

我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我

**Comment by zhoufanglu** [comment]
> > > 重启一下你的服务试试
> > 
> > 
> > 试过了
> 
> 我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我

加下qq吧，这公司项目，不太方便放网上， 735417031

**Comment by zhoufanglu** [comment]
> > > 重启一下你的服务试试
> > 
> > 
> > 试过了
> 
> 我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我

[项目地址](https://github.com/zhoufanglu/ocr-back-up) 我克隆了一份，你下载试试，路由地址`http://localhost:8080/logManage`

**Comment by Shimada666** [comment]
> > > > 重启一下你的服务试试
> > > 
> > > 
> > > 试过了
> > 
> > 
> > 我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我
> 
> [项目地址](https://github.com/zhoufanglu/ocr-back-up) 我克隆了一份，你下载试试，路由地址`http://localhost:8080/logManage`

![image](https://user-images.githubusercontent.com/33391300/134840030-00074e70-024c-437a-8f8f-09204c526a88.png)
我试了，虽然样式不太对劲，但是没发现组件本身的问题

**Comment by zhoufanglu** [comment]
> > > > > 重启一下你的服务试试
> > > > 
> > > > 
> > > > 试过了
> > > 
> > > 
> > > 我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我
> > 
> > 
> > [项目地址](https://github.com/zhoufanglu/ocr-back-up) 我克隆了一份，你下载试试，路由地址`http://localhost:8080/logManage`
> 
> ![image](https://user-images.githubusercontent.com/33391300/134840030-00074e70-024c-437a-8f8f-09204c526a88.png)
> 我试了，虽然样式不太对劲，但是没发现组件本身的问题

你本地没有报错吗？ 样式我在组件下面修改了，跟`element-table`样式冲突

**Comment by Shimada666** [comment]
> > > > > > 重启一下你的服务试试
> > > > > 
> > > > > 
> > > > > 试过了
> > > > 
> > > > 
> > > > 我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我
> > > 
> > > 
> > > [项目地址](https://github.com/zhoufanglu/ocr-back-up) 我克隆了一份，你下载试试，路由地址`http://localhost:8080/logManage`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/33391300/134840030-00074e70-024c-437a-8f8f-09204c526a88.png)
> > 我试了，虽然样式不太对劲，但是没发现组件本身的问题
> 
> 你本地没有报错吗？ 样式我在组件下面修改了，跟`element-table`样式冲突

没报错，你删掉 package-lock.json 等重新 npm 一下，刷新下缓存之类的再试下吧

**Comment by zhoufanglu** [comment]
> > > > > > > 重启一下你的服务试试
> > > > > > 
> > > > > > 
> > > > > > 试过了
> > > > > 
> > > > > 
> > > > > 我在 vue2 上测试是通过的。确保你安装了 composition-api。你可以试试强制刷新缓存或者重启后观察问题是否还在。如果还在，可以提供一个出现问题的 vue2 最小仓库给我
> > > > 
> > > > 
> > > > [项目地址](https://github.com/zhoufanglu/ocr-back-up) 我克隆了一份，你下载试试，路由地址`http://localhost:8080/logManage`
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/33391300/134840030-00074e70-024c-437a-8f8f-09204c526a88.png)
> > > 我试了，虽然样式不太对劲，但是没发现组件本身的问题
> > 
> > 
> > 你本地没有报错吗？ 样式我在组件下面修改了，跟`element-table`样式冲突
> 
> 没报错，你删掉 package-lock.json 等重新 npm 一下，刷新下缓存之类的再试下吧

我试了没用，还是报错，我是windows，样式是好的
![image](https://user-images.githubusercontent.com/24451091/134851069-a0ed3cad-2832-4a7b-a698-e9f3629a24e4.png)

**Comment by Shimada666** [comment]
![image](https://user-images.githubusercontent.com/33391300/134852006-81495b06-a341-4c49-a3c3-21d8bc446f2f.png)
应该和操作系统无关。我去掉了你的自定义 .d2h-code-side-linenumber 样式之后，效果呈现的是符合预期的，也没有 highlight 控制台报错，建议你再排查一下。浏览器是 chrome 90

**Comment by zhoufanglu** [comment]
![image](https://user-images.githubusercontent.com/24451091/134853487-c515d535-83da-4ad9-bb6b-96126815a5a5.png)
` .d2h-code-side-linenumber`样式我去除之后。。 好奇怪，我node_modules删除重新装了，package.lock也删了。。

**Comment by zhoufanglu** [comment]
> ![image](https://user-images.githubusercontent.com/24451091/134853487-c515d535-83da-4ad9-bb6b-96126815a5a5.png)
> ` .d2h-code-side-linenumber`样式我去除之后。。 好奇怪，我node_modules删除重新装了，package.lock也删了。。

解决了。。。 我淦， 我把node_modules重新删了，cnpm重新装就不报错了，npm就报错，好奇怪
