### ISSUE TITLE
统计信息支持中文

### ISSUE THREAD

**Issue by liyoungs** [Shimada666/v-code-diff#100]
右上角的统计信息中的additions 和deletions支持使用中文替代

**Comment by Shimada666** [comment]
其实我试下来用中文不好看，有考虑到使用者主要都是程序员，所以默认用了英文。我留个 slot 给你？你可以从 diff 事件中拿到统计信息的具体情况，然后自己绘制统计信息部分的 ui

**Comment by liyoungs** [comment]
好的，我试试diff事件。感谢博主的及时回复
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月13日(星期一) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Shimada666/v-code-diff] 统计信息支持中文 (Issue #100)





 
其实我试下来用中文不好看，有考虑到使用者主要都是程序员，所以默认用了英文。我留个 slot 给你？你可以从 diff 事件中拿到统计信息的具体情况，然后自己绘制统计信息部分的 ui

**Comment by Shimada666** [comment]
> 好的，我试试diff事件。感谢博主的及时回复 &nbsp; &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月13日(星期一) 上午10:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Shimada666/v-code-diff] 统计信息支持中文 (Issue #100) 其实我试下来用中文不好看，有考虑到使用者主要都是程序员，所以默认用了英文。我留个 slot 给你？你可以从 diff 事件中拿到统计信息的具体情况，然后自己绘制统计信息部分的 ui — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好，我这两天开发下 slot，届时你就能用了

**Comment by Shimada666** [comment]
1.8.0 有个 stat 插槽，diff 事件也可以获取统计情况，你可以自由定制要显示的内容了
