### ISSUE TITLE
复制的时候可以只复制一边的json嘛

### ISSUE THREAD

**Issue by suansuanGuo** [Shimada666/v-code-diff#102]
我只想复制pre的json数据 怎么设置？

**Comment by Shimada666** [comment]
难道不支持吗..这个功能应该是有的呀，你用的什么版本？

**Comment by suansuanGuo** [comment]
> 难道不支持吗..这个功能应该是有的呀，你用的什么版本？

1.5.0

**Comment by Shimada666** [comment]
可以升到最新版试试，目前最新版是1.7.2

**Comment by suansuanGuo** [comment]
> 可以升到最新版试试，目前最新版是1.7.2

我们现在的依赖仓只能下载到1.5.0 ，1.5.0版本可不可以配置什么来达到这个需求呢 或者是源码能不能更改什么来完成这个需求呢？

**Comment by Shimada666** [comment]
我建议是让你们负责npm团队的人同步下源，这种不应该让业务来解决。

**Comment by suansuanGuo** [comment]
> 我建议是让你们负责npm团队的人同步下源，这种不应该让业务来解决。

好吧 主要是同步源的话一套流程下来应该会比较慢

**Comment by Shimada666** [comment]
> > 我建议是让你们负责npm团队的人同步下源，这种不应该让业务来解决。
> 
> 好吧 主要是同步源的话一套流程下来应该会比较慢

确实，全量一般要一两天。如果你们公司有指定 npm 包按需同步的话倒是很快。但是这应该是基础设施的问题，摇他们解决就好。
如果着急需要，可以现在把当前源代码 clone 下来，改个名在你们公司内网 npm 源重新进行发布，然后装这个内网包就行
