### ISSUE TITLE
传入一个 JSON.stringify() 后的对象，然后输入想要对比的内容会非常的卡

### ISSUE THREAD

**Issue by dashixiong-11** [Shimada666/v-code-diff#112]
我有一个后端给我的对象 ，我拿到之后使用JSONstringify转换之后，有两个问题，1。转了之后没换行了，2那这个json字符串传入 oldstring ，然后我填写newstring的时候非常卡，咋回事 是我姿势不对？，我在demo页面试了下也是一样的，同一个对象，直接写没问题，但是转成json之后填入之后页面再输入东西就非常卡

**Comment by Shimada666** [comment]
你的 json 有多大？如果大几千行又开了高亮，卡也比较正常..
