### ISSUE TITLE
文本相同的行，为什么也提示不同，另外能不能弄个交流群呢哈哈

### ISSUE THREAD

**Issue by specialYmx** [Shimada666/v-code-diff#115]
![image](https://github.com/Shimada666/v-code-diff/assets/56808809/62b781b5-36c3-4d7e-afc0-c8cca6e7a982)

**Comment by specialYmx** [comment]
比如这个第三行，文本相同也有不同的“+”和背景色

**Comment by Shimada666** [comment]
我没复现出来，能否把两段文本提供一下？

**Comment by specialYmx** [comment]
> 我没复现出来，能否把两段文本提供一下？

原来文本
      78,c
      无更改的 
      文本




更改的文本
      79,c
      无更改的
      文本

**Comment by specialYmx** [comment]
> 我没复现出来，能否把两段文本提供一下？

![image](https://github.com/Shimada666/v-code-diff/assets/56808809/98fc41bb-b15f-442d-9fb0-501f67082863)
就自己弄得文本，然后从vscode里复制出来的😂

**Comment by specialYmx** [comment]
[aaa.txt](https://github.com/Shimada666/v-code-diff/files/13749415/aaa.txt)
刚发现复制过来的文本换行符都没了，这里面是我那两个文本

**Comment by Shimada666** [comment]
会不会是空格和tab的不同导致的

**Comment by specialYmx** [comment]
> 会不会是空格和tab的不同导致的

刚刚在“无更改的”这几个字前面只加了两个空格，也是提示文本不同，有背景色啊
![image](https://github.com/Shimada666/v-code-diff/assets/56808809/02afb2c4-652a-4a9e-875d-a9475d955f39)

**Comment by Shimada666** [comment]
<img width="385" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/62b77581-8bab-4516-a8b3-e85ea1cde004">
上一文本此处有空格

**Comment by specialYmx** [comment]
> <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/33391300/292657936-62b77581-8bab-4516-a8b3-e85ea1cde004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODMxNjUsIm5iZiI6MTcwMzQ4Mjg2NSwicGF0aCI6Ii8zMzM5MTMwMC8yOTI2NTc5MzYtNjJiNzc1ODEtOGJhYi00NTE2LWE4YjMtZTg1ZWExY2RlMDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA1NDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZjk1MGJmMTllZGFhNjRlN2ViMGQxOWNkMGZiZjZhOTg1YzU1ZWJjNjdlYWRjOTc0ZWVjYzMwMGMzMGQyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vXOU2Ow_ed_LV0bxjomu4ZpSrb9t_-WMkAfnsvVpIcA"> 上一文本此处有空格

感谢大佬，回复速度真快啊

**Comment by Gilbert5210** [comment]
<img width="1031" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/73e6535b-4d9d-47fe-9767-d188a5f74bd1">

@Shimada666 帮忙看下呢，我这边也不行
这行数据应该是modify，但是被显示为新增了

https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C11
