### ISSUE TITLE
能否增加一个点击跳到下一处不同功能呢

### ISSUE THREAD

**Issue by specialYmx** [Shimada666/v-code-diff#117]
大佬，能否增加一个点击跳到下一处不同功能呢，或者我自己实现有啥思路么，操作对比结果里面的dom方面吗

**Comment by Shimada666** [comment]
> 大佬，能否增加一个点击跳到下一处不同功能呢，或者我自己实现有啥思路么，操作对比结果里面的dom方面吗

有点重啊感觉，一般这种就是像 codemirror 之类的组件，内部实现搜索功能来代替浏览器的搜索。
我其实也还没看过类似的实现逻辑，但是我记得 codemirror、monaco-editor 之类的编辑器是有这个功能的

**Comment by QusaiSabri** [comment]
I have just created a Pull Request to add this feature in. 

I use this amazing library in my project and found the need to have a **Next** & **Previous** buttons to quickly jump to the next change specially on large files.

**Comment by 09473ZH** [comment]
https://github.com/Shimada666/v-code-diff/tree/v1.12.0 add this feature
