### ISSUE TITLE
1.0.0 version, better performance and more features.

### ISSUE THREAD

**Issue by Shimada666** [Shimada666/v-code-diff#12]
In the 0.x version, the html is created by the diff2html plugin to create an html string and then mounted on the element. Although this is simple, it is difficult to add custom functions, and the rendering and highlighting performance and effects are not ideal. For example, it is difficult for me to add a feature that clicks to expand and collapse the content.
In the 1.x version, I hope I can render html by myself, control the generation of html by myself, and it is easier to add some features, but this takes a lot of time, and I will try my best to improve it. If you need new features such as expanding and collapsing content, you can try editors such as monaco first, or comment below. If there are more people who need it, I will finish it as soon as possible. thank you for your support.

在 0.x 版本中，样式是通过 diff2html 插件创建出 html 字符串然后挂载到元素上的，这虽然简单，但很难添加自定义功能，渲染和高亮的性能与效果也不够理想。例如，我很难加入一个点击展开折叠内容的功能。
在 1.x 版本中，我希望能自己来渲染 html，自己把控 html 的生成，更容易增加自定义功能，但这需要时间，我会尽力完善它的。如果你有需要如展开折叠内容等新功能，可以先尝试 monaco 等编辑器，也可以在下方评论，如果需要它的人比较多，我会尽早地去完成它。感谢您的支持。

**Comment by Jadmin3** [comment]
大佬记得/r/n的问题也更新！QAQ

**Comment by Shimada666** [comment]
> 大佬记得/r/n的问题也更新！QAQ

这两天我就出个小版本更新下

**Comment by Jadmin3** [comment]
> 

希望周一能用上  哈哈

**Comment by Shimada666** [comment]
I am sorry for not releasing the new version on time due to busy work recently. Recently, I've started work on the new version and expect it to take a few more weekends. The new version will support many new features, so stay tuned!
