### ISSUE TITLE
文本应该为修改的数据，但是没有标记出修改的部分

### ISSUE THREAD

**Issue by Gilbert5210** [Shimada666/v-code-diff#125]
@Shimada666 帮忙看下呢，我这边也不行
这行数据应该是modify，但是被显示为新增了

https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C11

只有两行数据时候
<img width="1773" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/a7e8d6a5-c98e-4b35-af39-2bb91f8b0704">

但是新增一行数据就可以了
<img width="1764" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/21f09815-5f61-44a7-a8dc-efd395459722">

**Comment by Gilbert5210** [comment]
@Shimada666 
help

**Comment by Shimada666** [comment]
这是因为左边的第二行末尾有个换行符，而右边没有换行符导致的。

**Comment by Gilbert5210** [comment]
> 这是因为左边的第二行末尾有个换行符，而右边没有换行符导致的。

不是的，我两边都加换行符也不行。
因为是文本对比，我必须要加换行符
<img width="1766" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/8c187757-c393-4383-9383-d932d1c6f823">

**Comment by Gilbert5210** [comment]
或者你有没有好的建议，实现我对行文本的对比，我本来是个数组来的

**Comment by Shimada666** [comment]
我看错了，我没懂你题里的意思。你说的是哪行应该是修改，但被显示为新增

**Comment by Gilbert5210** [comment]
> 我看错了，我没懂你题里的意思。你说的是哪行应该是修改，但被显示为新增

@Shimada666 
我框选出来给你看看

<img width="1770" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/33773ef6-0584-4199-a2cd-fc1e1f658259">

**Comment by Gilbert5210** [comment]
看了源码，在这里会有差异
![image](https://github.com/Shimada666/v-code-diff/assets/17983736/9bdeec5c-d112-44e5-926f-ebf8f09498cf)
@Shimada666

**Comment by Shimada666** [comment]
噢，这是符合预期的，目前默认规则是当两边的差异行数不一致时，不具体显示 word 级的差异

**Comment by Gilbert5210** [comment]
> 噢，这是符合预期的，目前默认规则是当两边的差异行数不一致时，不具体显示 word 级的差异

他们差异行数是一致的哦，你仔细对比下这两行数据，我希望可以达到这个现实word级的差异
![image](https://github.com/Shimada666/v-code-diff/assets/17983736/c70b993c-22fb-4903-9d5d-1cf7b1ab9c56)
看下这个为什么就行呢？

**Comment by Shimada666** [comment]
你第一个图，删四行，增两行，差异行数不一致。
刚刚这个图，删两行，增两行，差异行数一致，所以才显示 word 级数据

**Comment by Gilbert5210** [comment]
> 你第一个图，删四行，增两行，差异行数不一致。 刚刚这个图，删两行，增两行，差异行数一致，所以才显示 word 级数据

你再认真看下这个吧
https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A8%2C10

**Comment by Gilbert5210** [comment]
@Shimada666 
咱们的插件非常好用，现在就卡在这个环节啦，希望大佬帮忙，我查了DiffMatchPatch库，实在没有思路

**Comment by Shimada666** [comment]
我理解你的意思。你也认真看下我的回复。
当检测到内容不同时，称为一处差异。这处差异可能是差异行数不等，也可能相等。
差异行数相等时，才会展示每行里 word 级的差异。不等时，只会展示行级别的差异。这就是你发的图的两种情况

**Comment by Shimada666** [comment]
<img width="2041" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/46e12b48-eb54-400b-a856-7bfa9e789932">
不等的情况，左4行，右2行，因此只展示行级别的不同

<img width="1809" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/933ea219-aae9-44bd-98e3-c89ddebb6c09">
相等的情况，左2行，右2行，因此展示每行内部的 word 级差异

**Comment by Gilbert5210** [comment]
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/33391300/297946031-46e12b48-eb54-400b-a856-7bfa9e789932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYwMzEtNDZlMTJiNDgtZWI1NC00MDBiLWE4NTYtN2JmYTllNzg5OTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmEwMWQ2MjM3N2Q3MWQ1NTQyMTI4NTIyZDUxODEzMWI3MDJkMWI3ZjZkOGYwNWE0OWU5ODY5OWYzZTU4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GYcPbvAwgk3VhZqS-j3F4mjWHkWYwkP1T8h58ohs9iU"> 不等的情况，左4行，右2行，因此只展示行级别的不同 <img alt="image" width="1809" src="https://private-user-images.githubusercontent.com/33391300/297946211-933ea219-aae9-44bd-98e3-c89ddebb6c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYyMTEtOTMzZWEyMTktYWFlOS00NGJkLTk4ZTMtYzg5ZGRlYmI2YzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NzcxZThhNWQ5YTk1ZWVmMzE5NzkwZjEyYWM5MGRkNGFhMWQ2YWYzZGNiNWJiYzlmZDFhMmY1ZjNkMmJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOm9M4R1o21lHu-eleeNZiSBN_6NWhiFFdsiZ2VRmsY"> 相等的情况，左2行，右2行，因此展示每行内部的 word 级差异


你后面说的这个案例不能理解
这个情况为什么是相等的？

--------
而且真实案例中，左边是20个数据，右边是2-4条

**Comment by Gilbert5210** [comment]
或者抛开这个，有没有办法让我实现，有相同的数据的话，进行word级差异展示
https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C11
就这个数据中，可以实现word级别的对比

**Comment by 09473ZH** [comment]
> > <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/33391300/297946031-46e12b48-eb54-400b-a856-7bfa9e789932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYwMzEtNDZlMTJiNDgtZWI1NC00MDBiLWE4NTYtN2JmYTllNzg5OTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmEwMWQ2MjM3N2Q3MWQ1NTQyMTI4NTIyZDUxODEzMWI3MDJkMWI3ZjZkOGYwNWE0OWU5ODY5OWYzZTU4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GYcPbvAwgk3VhZqS-j3F4mjWHkWYwkP1T8h58ohs9iU"> 不等的情况，左4行，右2行，因此只展示行级别的不同 <img alt="image" width="1809" src="https://private-user-images.githubusercontent.com/33391300/297946211-933ea219-aae9-44bd-98e3-c89ddebb6c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYyMTEtOTMzZWEyMTktYWFlOS00NGJkLTk4ZTMtYzg5ZGRlYmI2YzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NzcxZThhNWQ5YTk1ZWVmMzE5NzkwZjEyYWM5MGRkNGFhMWQ2YWYzZGNiNWJiYzlmZDFhMmY1ZjNkMmJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOm9M4R1o21lHu-eleeNZiSBN_6NWhiFFdsiZ2VRmsY"> 相等的情况，左2行，右2行，因此展示每行内部的 word 级差异
> 
> 你后面说的这个案例不能理解 这个情况为什么是相等的？
> 
> 而且真实案例中，左边是20个数据，右边是2-4条


首先你要明确，这是文件与文件的之间的比较；当两个文件行数相同时：
<img width="943" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/43346380/d9b8f9e2-95e3-48a1-8d58-23719d2b237a">
<img width="926" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/43346380/11a1de85-3a4c-4ad0-833a-b37eef3a5a29">（这种情况，第四行是换行符）；
当两个文件行数不同时：
<img width="1173" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/43346380/c6a67893-aa6d-48c4-84a7-361c6eeb67d7">
而你的数据很明显两个行数不一样。
当检测到内容不同时，称为一处差异。这处差异可能是差异行数不等，也可能相等。这时候是属于差异行数的情况，所以没有显示`word`差异

**Comment by 09473ZH** [comment]
> > > <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/33391300/297946031-46e12b48-eb54-400b-a856-7bfa9e789932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYwMzEtNDZlMTJiNDgtZWI1NC00MDBiLWE4NTYtN2JmYTllNzg5OTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmEwMWQ2MjM3N2Q3MWQ1NTQyMTI4NTIyZDUxODEzMWI3MDJkMWI3ZjZkOGYwNWE0OWU5ODY5OWYzZTU4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GYcPbvAwgk3VhZqS-j3F4mjWHkWYwkP1T8h58ohs9iU"> 不等的情况，左4行，右2行，因此只展示行级别的不同 <img alt="image" width="1809" src="https://private-user-images.githubusercontent.com/33391300/297946211-933ea219-aae9-44bd-98e3-c89ddebb6c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYyMTEtOTMzZWEyMTktYWFlOS00NGJkLTk4ZTMtYzg5ZGRlYmI2YzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NzcxZThhNWQ5YTk1ZWVmMzE5NzkwZjEyYWM5MGRkNGFhMWQ2YWYzZGNiNWJiYzlmZDFhMmY1ZjNkMmJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOm9M4R1o21lHu-eleeNZiSBN_6NWhiFFdsiZ2VRmsY"> 相等的情况，左2行，右2行，因此展示每行内部的 word 级差异
> > 
> > 
> > 你后面说的这个案例不能理解 这个情况为什么是相等的？
> > 而且真实案例中，左边是20个数据，右边是2-4条
> 
> 首先你要明确，这是文件与文件的之间的比较；当两个文件行数相同时： <img alt="image" width="943" src="https://private-user-images.githubusercontent.com/43346380/297948730-d9b8f9e2-95e3-48a1-8d58-23719d2b237a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzcyMzcsIm5iZiI6MTcwNTYzNjkzNywicGF0aCI6Ii80MzM0NjM4MC8yOTc5NDg3MzAtZDliOGY5ZTItOTVlMy00OGExLThkNTgtMjM3MTlkMmIyMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZTczMjk5MzEwYzVmZDBmZTEzZDI2MDIwM2NlMTQ2Mjg4N2JiMjUxZDBlODMzZDEyYWVmZTRjYzgzMjJkNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-jK31Z48FESFqkAAwTp4suS5L5dP5XN9FxS_qHcAxs"> <img alt="image" width="926" src="https://private-user-images.githubusercontent.com/43346380/297949067-11a1de85-3a4c-4ad0-833a-b37eef3a5a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzcyMzcsIm5iZiI6MTcwNTYzNjkzNywicGF0aCI6Ii80MzM0NjM4MC8yOTc5NDkwNjctMTFhMWRlODUtM2E0Yy00YWQwLTgzM2EtYjM3ZWVmM2E1YTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMzZlYTZmZDMxMjYyYTZhMjA4NjY3ODg5M2VjZDY0YjdkNjUwZmQxYmM0MzdhMzk4MzliYTA5N2QyMzNiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EKSpMpc3Z3_nTXjqRjk336_yWnM0Sc-JoU-jwWs1vdg">（这种情况，第四行是换行符）； 当两个文件行数不同时： <img alt="image" width="1173" src="https://private-user-images.githubusercontent.com/43346380/297949150-c6a67893-aa6d-48c4-84a7-361c6eeb67d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzcyMzcsIm5iZiI6MTcwNTYzNjkzNywicGF0aCI6Ii80MzM0NjM4MC8yOTc5NDkxNTAtYzZhNjc4OTMtYWE2ZC00OGM0LTg0YTctMzYxYzZlZWI2N2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViOGYwZDMxOWQzMjk5OTllYjA2MjI5NmU3MjFiZWU0MjQ5MjZhMjgwOWY2YzdkNmRjMzdmYTYwODIyOWVhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QAU3q3ejJcgSfs8rajb8CSKWbB_4fkwPONTlTyJySfY"> 而你的数据很明显两个行数不一样。 当检测到内容不同时，称为一处差异。这处差异可能是差异行数不等，也可能相等。这时候是属于差异行数的情况，所以没有显示`word`差异

所以 [codesandbox](https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C11)
这个数据中，你只要把右边的行数补齐成左边一致的就可以了
<img width="1589" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/43346380/460049d2-fe31-4cab-91e0-595adf20078f">

**Comment by 09473ZH** [comment]
> 或者抛开这个，有没有办法让我实现，有相同的数据的话，进行word级差异展示 https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C11 就这个数据中，可以实现word级别的对比


所以 [codesandbox](https://codesandbox.io/p/devbox/codediffdemo-fkwplt?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A10%2C11)
这个数据中，你只要把右边的行数补齐成左边一致的就可以了
<img width="1589" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/43346380/460049d2-fe31-4cab-91e0-595adf20078f">

**Comment by Gilbert5210** [comment]
> > > <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/33391300/297946031-46e12b48-eb54-400b-a856-7bfa9e789932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYwMzEtNDZlMTJiNDgtZWI1NC00MDBiLWE4NTYtN2JmYTllNzg5OTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmEwMWQ2MjM3N2Q3MWQ1NTQyMTI4NTIyZDUxODEzMWI3MDJkMWI3ZjZkOGYwNWE0OWU5ODY5OWYzZTU4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GYcPbvAwgk3VhZqS-j3F4mjWHkWYwkP1T8h58ohs9iU"> 不等的情况，左4行，右2行，因此只展示行级别的不同 <img alt="image" width="1809" src="https://private-user-images.githubusercontent.com/33391300/297946211-933ea219-aae9-44bd-98e3-c89ddebb6c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzU2NTQsIm5iZiI6MTcwNTYzNTM1NCwicGF0aCI6Ii8zMzM5MTMwMC8yOTc5NDYyMTEtOTMzZWEyMTktYWFlOS00NGJkLTk4ZTMtYzg5ZGRlYmI2YzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NzcxZThhNWQ5YTk1ZWVmMzE5NzkwZjEyYWM5MGRkNGFhMWQ2YWYzZGNiNWJiYzlmZDFhMmY1ZjNkMmJmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOm9M4R1o21lHu-eleeNZiSBN_6NWhiFFdsiZ2VRmsY"> 相等的情况，左2行，右2行，因此展示每行内部的 word 级差异
> > 
> > 
> > 你后面说的这个案例不能理解 这个情况为什么是相等的？
> > 而且真实案例中，左边是20个数据，右边是2-4条
> 
> 首先你要明确，这是文件与文件的之间的比较；当两个文件行数相同时： <img alt="image" width="943" src="https://private-user-images.githubusercontent.com/43346380/297948730-d9b8f9e2-95e3-48a1-8d58-23719d2b237a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDU0ODUsIm5iZiI6MTcwNTY0NTE4NSwicGF0aCI6Ii80MzM0NjM4MC8yOTc5NDg3MzAtZDliOGY5ZTItOTVlMy00OGExLThkNTgtMjM3MTlkMmIyMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZDU1YTQxZGYxNTJjMTRkNWM2NWU3NmUwNWQ2NjMxMmEyNDExODdmMDY5NmYzOTVlMjM4MGQzNDZkNTg4MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._nyB0oBDgdVBeIKoHbkCa1SqH0VBCixt2Pkka9eWcZc"> <img alt="image" width="926" src="https://private-user-images.githubusercontent.com/43346380/297949067-11a1de85-3a4c-4ad0-833a-b37eef3a5a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDU0ODUsIm5iZiI6MTcwNTY0NTE4NSwicGF0aCI6Ii80MzM0NjM4MC8yOTc5NDkwNjctMTFhMWRlODUtM2E0Yy00YWQwLTgzM2EtYjM3ZWVmM2E1YTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTZkYTgzMjkyM2JmNzdlZDc0NmY4NmMzZDMxMzJjM2UxY2Q3ZjE1OWFmOTU5OGYzNGEzNDI0ZDY2YjM1YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pAdL1MqO-PwvxPf-qyPKtu13ZjRGfH2Z0r9oNfS-pvQ">（这种情况，第四行是换行符）； 当两个文件行数不同时： <img alt="image" width="1173" src="https://private-user-images.githubusercontent.com/43346380/297949150-c6a67893-aa6d-48c4-84a7-361c6eeb67d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDU0ODUsIm5iZiI6MTcwNTY0NTE4NSwicGF0aCI6Ii80MzM0NjM4MC8yOTc5NDkxNTAtYzZhNjc4OTMtYWE2ZC00OGM0LTg0YTctMzYxYzZlZWI2N2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzU0Zjg0YzEzOGY0M2RiYmVkYWM0ZWZiOTJhMjlmN2U2ODIxYjVjOGFkMDcxMmFkYjFmZDJkYzdmNmY4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4BkSBXxG1NmB0reKLtl1aJcjcypsqlZdtHxU8k6agY"> 而你的数据很明显两个行数不一样。 当检测到内容不同时，称为一处差异。这处差异可能是差异行数不等，也可能相等。这时候是属于差异行数的情况，所以没有显示`word`差异




根据你说的，这个好像不能成立，只要我在中间有相同的，他就可以触发word差异
<img width="1563" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/fc6b6ca4-848d-444c-91fe-7b5ca9ff87ca">

**Comment by 09473ZH** [comment]
不好意思，之前`文件与文件之间`是笔误了，现已更正。你可以这样理解：解析结果是：相同文本 --> 一块差异（两个段落之间行数相同，word 差异） --> diff到文本是相同的 --> 一块差异（两个段落之间行数不同）；

**Comment by Gilbert5210** [comment]
@09473ZH 
在不添加空行的情况，能不能让我实现这个两行数据的时候，也是word差异展示？

**Comment by 09473ZH** [comment]
> @09473ZH 在不添加空行的情况，能不能让我实现这个两行数据的时候，也是word差异展示？
不能的。添加空行本来也不是个现实的做法，只是为了说明更清楚而已。

**Comment by Gilbert5210** [comment]
> > @09473ZH 在不添加空行的情况，能不能让我实现这个两行数据的时候，也是word差异展示？
> 
> 不能的。添加空行本来也不是个现实的做法，只是为了说明更清楚而已。


那真实需求中，这里就存在问题呢，我看到的前面两行其实只做了修改，但是被标记出来是删除后新增。
或者说，我现在必须要能去work差异的方式去展示的话，你有好的解决方案吗

**Comment by 09473ZH** [comment]
> 那真实需求中，这里就存在问题呢，我看到的前面两行其实只做了修改，但是被标记出来是删除后新增。 或者说，我现在必须要能去work差异的方式去展示的话，你有好的解决方案吗

目前是以`github`的效果为参照的，你说的那种情况不支持呢

**Comment by Gilbert5210** [comment]
<img width="979" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/17983736/1fe73896-953f-4bc8-81db-3fce1f6e783e">
@09473ZH 
看下，这种都没法支持按照文本对比出差异
