### ISSUE TITLE
1000行的json数据对比，浏览器会卡死，有办法吗？

### ISSUE THREAD

**Issue by mxian** [Shimada666/v-code-diff#127]
大佬们，是我用的不对还是怎么的，数据量小的时候，没什么问题。但如果是两个1000行左右的json字符串，浏览器就会卡死了。

我是把对比组件放在el-dialog里用的

**Comment by Shimada666** [comment]
一千行不至于卡死，可否提供下两段 json 内容？

**Comment by mxian** [comment]
> 一千行不至于卡死，可否提供下两段 json 内容？

哦，不对大佬，看错了，1000多个节点，一共7w行
[Uploading 7w_Json.txt…]()

**Comment by Shimada666** [comment]
> > 一千行不至于卡死，可否提供下两段 json 内容？
> 
> 哦，不对大佬，看错了，1000多个节点，一共7w行 Uploading 7w_Json.txt…

...卡死是正常的，有点过大了，属于你放 ide 里都会提示你过大的情况，可能可以考虑下别的技术方案..不过你这链接是怎么回事？

**Comment by Shimada666** [comment]
可以先用 monaco editor，性能巨好，7w 行好像也没问题。我这插件性能上暂时还没跟上

**Comment by mxian** [comment]
> 可以先用 monaco editor，性能巨好，7w 行好像也没问题。我这插件性能上暂时还没跟上

我去试一下，谢谢大佬提点

**Comment by mxian** [comment]
monaco editor已经用上了，的确性能非常好，对比两个7w行的json，毫无压力，感谢指点！
