### ISSUE TITLE
打包上线后，引入插件的页面报错

### ISSUE THREAD

**Issue by junluoluo** [Shimada666/v-code-diff#129]
![微信图片_20240228160913](https://github.com/Shimada666/v-code-diff/assets/49894989/c980853b-7a71-40f1-b5ec-69a0f3746ecd)
不引入插件时就不会报错，大佬帮忙看看这是哪出的问题？使用的是"v-code-diff": "^1.9.0"

**Comment by junluoluo** [comment]
补充说明一下，用的vue3+ts，本地运行都没问题，本地预览也是报同样的问题，不管是全局引入还是局部引入build后都会报这个错，区别是全局引入刚进入项目就报错，局部是打开引入的界面才报错

**Comment by junluoluo** [comment]
找到问题了，esbuild 中配置了 pure, 移除了所有 console.log 后, 会出现该错误信息
解决办法：1、暂时关闭pure配置项
                  2、使用drop配置项来完全移除console.log，代价是 consoleerror等方法也会移除。 drop: ['console", 'debugger']

**Comment by Shimada666** [comment]
我代码里也没 console.log 啊..
其他版本是否正常？如 1.8.0

**Comment by junluoluo** [comment]
![image](https://github.com/Shimada666/v-code-diff/assets/49894989/f82bfe49-c015-4f2f-9907-bd3a3956a3b1)

**Comment by Shimada666** [comment]
> ![image](https://private-user-images.githubusercontent.com/49894989/309116814-f82bfe49-c015-4f2f-9907-bd3a3956a3b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjI0MjAsIm5iZiI6MTcwOTI2MjEyMCwicGF0aCI6Ii80OTg5NDk4OS8zMDkxMTY4MTQtZjgyYmZlNDktYzAxNS00ZjJmLTk5MDctYmQzYTM5NTZhM2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAzMDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OTc2NTA1ZDMzM2IyZDEzMzdmZGFhNWQ1ZTAxYWE2OWVhM2UzNTc3MzI4ZDA3ZDc2MjA2ZTI4MGQ0NDEzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chSexLL32aU7OEsJ5z5sHsZJfGrnpxxx6OOMG--EH2I)

看了下，是highlight.js 引入的，他们会在控制台打警告，即使我没用那个 api。我看看能不能升级他们新版本去掉警告

**Comment by Shimada666** [comment]
我看了下 我好像已经是最新版了

**Comment by Shimada666** [comment]
从库的方面不好解决，这是 highlight 带的警告，打包是会打包进来的。
有一个思路，配置 eslint 规则 'no-console': ["error", { allow: ["warn", "error"] }]，允许 error、warn 级 console。提交时配置 git hook 自动 eslint 修复文件，构建时校验代码是否符合 eslint 规则，不正常不允许构建，可以达到你的目的
