### ISSUE TITLE
Compare line by line even if the number of rows is different [Feature]

### ISSUE THREAD

**Issue by leandroalexandreipb** [Shimada666/v-code-diff#132]
Hello, 
Is there any possibility to allow us to compare line by line, for example if we have a different number of lines but still want to have the differences between the lines at this point it is not possible, I show an example in the image below.
<img width="536" alt="vue-code-diff" src="https://github.com/Shimada666/v-code-diff/assets/127799619/d4caa847-60c6-49ad-8ae4-5bb003618cdd">
A prop could be used to choose the type of comparison.

Thank you for the excellent work.
Carefully,
Kalallit

**Comment by 09473ZH** [comment]
We have considered supporting this feature. The reason it wasn't implemented later is that line-by-line comparison may not be very effective in comparing differences when line numbers vary. Perhaps in the next version, we will implement this feature if you need.

**Comment by leandroalexandreipb** [comment]
If you can do that that would be awesome👍 
Thanks for the quick response

**Comment by 09473ZH** [comment]
Hi~The new feature has been updated. You can try it out at [demo](https://shimada666.github.io/v-code-diff/) by selecting the 'Force Inline Comparison' option.
