### ISSUE TITLE
对比无差别时，显示优化建议

### ISSUE THREAD

**Issue by liuzm7188** [Shimada666/v-code-diff#14]
![image](https://user-images.githubusercontent.com/20579366/141882251-198cebcb-6703-4d9b-8aee-783266bd41b4.png)
![image](https://user-images.githubusercontent.com/20579366/141882549-faff5484-c7eb-4993-a9a6-bd6471876741.png)
使用过程中发现，"CHANGED" 始终在，不会有差异变化
建议：对比无差异时，"CHANGED" =》 "NO CHANGED" 标记绿色

**Comment by Shimada666** [comment]
这个是 diff2html 自动生成的，目前感觉这个 changed 没啥用。也许后续将这一栏隐藏掉是个好选择
