### ISSUE TITLE
选中对比后的内容，点击右键时 光标消失了，变成了取消选中状态，这个操作如何阻止呢，给大佬跪了

### ISSUE THREAD

**Issue by WANGXIAOYU1995** [Shimada666/v-code-diff#145]
![image](https://github.com/Shimada666/v-code-diff/assets/109521682/e004ff7a-4962-4478-99d7-67ea2ad9e403)

**Comment by WANGXIAOYU1995** [comment]
感觉是个小问题，但是又找不到解决办法，阻止右键默认行为也不生效。。

**Comment by WANGXIAOYU1995** [comment]
作者什么时候上线啊

**Comment by Shimada666** [comment]
我研究一下

**Comment by WANGXIAOYU1995** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WANGXIAOYU1995** [comment]
谢谢老板 老板发大财

**Comment by WANGXIAOYU1995** [comment]
这么难

**Comment by Shimada666** [comment]
1.12.1修复了

**Comment by WANGXIAOYU1995** [comment]
现在才看到  多谢老板 我升级版本试一下
