### ISSUE TITLE
对比内容出错，很严重的错误

### ISSUE THREAD

**Issue by kentLin0** [Shimada666/v-code-diff#148]
![image](https://github.com/user-attachments/assets/3a5f8127-56d0-419e-a3c4-6e6d10a6d436)
整个文件只有最后末尾不同，但是对比出来的结果会把前面所有内容标记为删除，然后后面全部标记为新增，这个是什么原因导致的？

**Comment by kentLin0** [comment]
![image](https://github.com/user-attachments/assets/a05d0f5c-dd9a-46d5-882a-a0f6870b1e38)

**Comment by Shimada666** [comment]
能否提供下原始文本

**Comment by kentLin0** [comment]
找到原因了，原始文件里面每一个换行符后面多了一个空格导致的，:no-diff-line-feed="true"，就正常了

**Comment by Shimada666** [comment]
好的
