### ISSUE TITLE
isShowNoChange时头部信息需要隐藏

### ISSUE THREAD

**Issue by dongkaifei** [Shimada666/v-code-diff#15]
`if (props.isShowNoChange) {
    oldString = 'File Without Change\tOldString: ======================== \n' + oldString
    newString = 'File Without Change\tNewString: ======================== \n' + newString
  }`
这一段可不可以去掉发一个小版本呢？

**Comment by Shimada666** [comment]
你说的是，当有数据变化时，这段不显示么

**Comment by dongkaifei** [comment]
![image](https://user-images.githubusercontent.com/23350202/142969882-c9ab808d-7cda-4862-8a7e-f8d17f3a07f6.png)
对的，希望这里不显示这个

**Comment by dongkaifei** [comment]
对的，希望不展示这行
![image](https://user-images.githubusercontent.com/23350202/142970000-8939f6fa-3942-43f5-8e77-3f9621ed3bc9.png)

**Comment by Shimada666** [comment]
> 对的，希望不展示这行 ![image](https://user-images.githubusercontent.com/23350202/142970000-8939f6fa-3942-43f5-8e77-3f9621ed3bc9.png)

试试 0.3.7 版本

**Comment by dongkaifei** [comment]
看到了，感谢

**Comment by xiang0308** [comment]
0.3.11 版本 还是没有隐藏头部信息，是需要传入其他参数吗？

**Comment by xiang0308** [comment]
![image](https://user-images.githubusercontent.com/16834032/183029994-e1822cc5-1374-4a5e-a337-5ce3092105c1.png)
希望当无数据变化时，这段文案不显示。

**Comment by Shimada666** [comment]
> 0.3.11 版本 还是没有隐藏头部信息，是需要传入其他参数吗？

不是呀，当内容相同的时候，就是会显示这段。如果不同时就不会显示

**Comment by Shimada666** [comment]
> ![image](https://user-images.githubusercontent.com/16834032/183029994-e1822cc5-1374-4a5e-a337-5ce3092105c1.png) 希望当无数据变化时，这段文案不显示。

那其实现有框架目前并不好做到.. 因为相同时他就 diff 就没内容了，也展示不出来源代码了

**Comment by xiang0308** [comment]
> > 0.3.11 版本 还是没有隐藏头部信息，是需要传入其他参数吗？
> 
> 不是呀，当内容相同的时候，就是会显示这段。如果不同时就不会显示

在实际应用场景中，这两段文案是不需要的，可以加下开关控制下吗？

**Comment by xiang0308** [comment]
![issue](https://user-images.githubusercontent.com/16834032/183872281-9ff8cea3-a750-457e-95da-6c27cca92426.jpg)
大佬，诉求如截图所示这样的，目前在实际应用中需要手动hack来处理隐藏。

**Comment by Shimada666** [comment]
> > > 0.3.11 版本 还是没有隐藏头部信息，是需要传入其他参数吗？
> > 
> > 
> > 不是呀，当内容相同的时候，就是会显示这段。如果不同时就不会显示
> 
> 在实际应用场景中，这两段文案是不需要的，可以加下开关控制下吗？

这个主要是感觉没啥好的办法呀，这个功能是从 vue-code-diff 移植过来的，底层是 diff2html。diff2html 接收一段 git diff string 作为输入，然后解析输出 html 展示。而这是由前后不同的 diff string 使用 diff 库进行 diff 出的。如果内容完全相同，那 diff string 就不会有内容，因此加了这第一行保证 git diff string 有内容。如果短期内要实现你这个功能，有一种办法是如果判断内容完全相等，就直接伪造 git diff string来显示，这样确实是可以达到近似的效果的，要不要这么支持还要评估一下。长期来看我觉得还是摆脱 diff2html 的限制比较好

**Comment by xiang0308** [comment]
> > > > 0.3.11 版本 还是没有隐藏头部信息，是需要传入其他参数吗？
> > > 
> > > 
> > > 不是呀，当内容相同的时候，就是会显示这段。如果不同时就不会显示
> > 
> > 
> > 在实际应用场景中，这两段文案是不需要的，可以加下开关控制下吗？
> 
> 这个主要是感觉没啥好的办法呀，这个功能是从 vue-code-diff 移植过来的，底层是 diff2html。diff2html 接收一段 git diff string 作为输入，然后解析输出 html 展示。而这是由前后不同的 diff string 使用 diff 库进行 diff 出的。如果内容完全相同，那 diff string 就不会有内容，因此加了这第一行保证 git diff string 有内容。如果短期内要实现你这个功能，有一种办法是如果判断内容完全相等，就直接伪造 git diff string来显示，这样确实是可以达到近似的效果的，要不要这么支持还要评估一下。长期来看我觉得还是摆脱 diff2html 的限制比较好

嗯嗯，了解。 不过短期还是希望能支持这个功能，体验上会好很多，哈哈。长期的话，能否摆脱 diff2html 的限制，有机会可以和大佬一起探究。
