### ISSUE TITLE
文件对比会受 /r /n影响

### ISSUE THREAD

**Issue by Jadmin3** [Shimada666/v-code-diff#16]
文件对比会受 /r /n影响  内容是一样的 但是因为看不见的/r  /n导致差异  可以忽略这些差异吗

**Comment by Shimada666** [comment]
#6 和这个一样么？还是说有的换行符是 \r\n 有的换行符是 \n 造成的diff错误？

**Comment by Jadmin3** [comment]
@Shimada666 对对对  就是因为有的是\r  有的是\n 导致的这种情况  大佬 请问有啥解决方案不
![image](https://user-images.githubusercontent.com/34308316/144382200-86eb9fcd-306c-4e2f-b7fe-fb0083c16c48.png)

**Comment by Shimada666** [comment]
> @Shimada666 对对对 就是因为有的是\r 有的是\n 导致的这种情况 大佬 请问有啥解决方案不 ![image](https://user-images.githubusercontent.com/34308316/144382200-86eb9fcd-306c-4e2f-b7fe-fb0083c16c48.png)

可以先用正则把字符串替换一下，\r\n 换成 \n，后面我搞个 prop 支持一下
```javascript
const raw = '123\r\n123'
const result = raw.replace(/(\r\n)/g, '\n')
```

**Comment by Jadmin3** [comment]
@Shimada666 大佬 大佬  哇  解决了！！！！ 大佬赶紧更新~~等你  0.0

**Comment by Shimada666** [comment]
0.3.8 增加了 Prop: noDiffLineFeed，开启后不会diff换行符
