### ISSUE TITLE
有的时候只想语法高亮不想对比可以支持不~

### ISSUE THREAD

**Issue by Jadmin3** [Shimada666/v-code-diff#17]
有的时候只想语法高亮不想对比可以支持不~  大佬

**Comment by Shimada666** [comment]
> 有的时候只想语法高亮不想对比可以支持不~ 大佬

那直接用highlight.js不就好了嘛

**Comment by Jadmin3** [comment]
> > 有的时候只想语法高亮不想对比可以支持不~ 大佬
> 
> 那直接用highlight.js不就好了嘛

我用了  但是我发现会和你的插件冲突。。。你插件的底色会变。。

**Comment by Shimada666** [comment]
> > > 有的时候只想语法高亮不想对比可以支持不~ 大佬
> > 
> > 
> > 那直接用highlight.js不就好了嘛
> 
> 我用了 但是我发现会和你的插件冲突。。。你插件的底色会变。。

能截个图么，我可能需要 css scope 一下
