### ISSUE TITLE
可以行号不对不爆红，只在有内容不一致时候爆红吗

### ISSUE THREAD

**Issue by Jadmin3** [Shimada666/v-code-diff#19]
可以行号不对不爆红，只在有内容不一致时候爆红吗？大佬
![image](https://user-images.githubusercontent.com/34308316/147050669-cc210d68-ad8b-4d7c-9e85-9a0c5390c896.png)

**Comment by Shimada666** [comment]
发下 diff 文本我先看看

**Comment by Jadmin3** [comment]
> 

文本有些敏感，能单独加您个wechat发给你嘛

**Comment by Shimada666** [comment]
> > 
> 
> 文本有些敏感，能单独加您个wechat发给你嘛

你脱敏后发我

**Comment by Jadmin3** [comment]
我代码写错了。。。
