### ISSUE TITLE
请问有计划支持深色模式吗？

### ISSUE THREAD

**Issue by keemozhang** [Shimada666/v-code-diff#20]

**Comment by Shimada666** [comment]
啊这。。。。还有这种需求吗

**Comment by Shimada666** [comment]
我后面考虑支持深色模式，但是支持时间不确定，可能要出1.0后支持了

**Comment by keemozhang** [comment]
好的，谢谢

**Comment by Pancake-Q** [comment]
同文现在支持深色主题吗？

**Comment by Shimada666** [comment]
> 同文现在支持深色主题吗？

还不支持，估计下个或者下下个版本支持，比较多人用的话我开发优先级就提前些

**Comment by Pancake-Q** [comment]
https://github.com/hoiheart/vue-diff?ref=morioh.com&utm_source=morioh.com#introduction 想这个
能够引入highlight 支持的主题还是挺多的

**Comment by Shimada666** [comment]
> https://github.com/hoiheart/vue-diff?ref=morioh.com&utm_source=morioh.com#introduction 像这个 能够引入highlight 支持的主题还是挺多的

应该短期内不会支持自定义主题，只支持普通模式/深色模式两套。样式直接从 github code diff 扒
