### ISSUE TITLE
请问下怎么控制代码区域高度

### ISSUE THREAD

**Issue by sangthian** [Shimada666/v-code-diff#21]
要怎么才能设置代码比较区域的最大高度，麻烦了

**Comment by sangthian** [comment]
已解决

**Comment by nozbwang** [comment]
> 已解决

怎么解决的？我的现在内容行数就很多，导致一开始都看不到底部水平滚动条。

**Comment by Shimada666** [comment]
> > 已解决
> 
> 怎么解决的？我的现在内容行数就很多，导致一开始都看不到底部水平滚动条。

可以通过升级到最新版本，使用 maxHeight 参数解决
