### ISSUE TITLE
使用时直接报错

### ISSUE THREAD

**Issue by stefenson** [Shimada666/v-code-diff#23]
提示 diff2html 没有 diff.js 文件，去目录看了一下确实没有，应该是 diff2html 版本更改造成的？
希望修复一下。

**Comment by Shimada666** [comment]
谢谢反馈！我去看一下

**Comment by Shimada666** [comment]
抱歉 我创建了一个新项目 没能复现这个错。你删掉 nodemodules 重建一下呢？我测试发现 diff2html 安装的是 3.4.16 版本
我的 yarn.lock
```yaml
diff2html@^3.4.5:
  version "3.4.16"
  resolved "https://registry.npmjs.org/diff2html/-/diff2html-3.4.16.tgz#3d27e88594fa0e1ab954cc11e90895f9fa7b002d"
  integrity sha512-KfkvEoZTJertjoGPYFLn8n0yRdvzJcHvFJpJwbIxUlHU9x6qqhRZEM+TlgtU09jdLqRZAQyWFoxPiP6HeT2IYA==
  dependencies:
    diff "5.0.0"
    hogan.js "3.0.2"
  optionalDependencies:
    highlight.js "11.2.0"
```

**Comment by stefenson** [comment]
我这儿也是这个版本，但是不知道为啥就是不装 diff 这个包
![image](https://user-images.githubusercontent.com/17709715/162420777-a789dc02-cd54-4815-a0bd-17d35b7198cf.png)
![image](https://user-images.githubusercontent.com/17709715/162420869-d63496c4-7b48-4bd1-81a6-5edda82b698f.png)
大佬有啥头绪吗？

**Comment by stefenson** [comment]
我手动在 diff2html 目录里面执行了一下 npm install diff 可以用了，是不是依赖写到 dependencies 里面好一点？

**Comment by Shimada666** [comment]
![image](https://user-images.githubusercontent.com/33391300/162421705-45d1a850-5780-48da-9e97-a3b50229c65e.png)
我也没有，你不如把 lock 文件和 Node modules 删了重新安装下试试... diff 这个依赖是在 Dependencies 的

**Comment by Shimada666** [comment]
> 我手动在 diff2html 目录里面执行了一下 npm install diff 可以用了，是不是依赖写到 dependencies 里面好一点？

你这样换台机器就不行了，还是建议看一下问题为什么发生
