### ISSUE TITLE
vue3+vite可以正常打包，但是打开项目后报错

### ISSUE THREAD

**Issue by tdw143** [Shimada666/v-code-diff#24]
Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".
该怎么解决。。。

**Comment by Shimada666** [comment]
问题描述太少了，这种看起来是你们自己代码问题。能提供个最小的可复现的demo么？

**Comment by tdw143** [comment]
本地用没问题，打包也没问题，部署后打开项目就报错了，说我vue的引用路径不对，我不用这个库的时候却是好的，不知道问题出在哪里。。。截图也上传不了。。。

**Comment by tdw143** [comment]
![微信图片_20220419184537](https://user-images.githubusercontent.com/82980777/163990067-bd4b5fce-5b5a-4cb5-bd57-861885f159cc.png)

**Comment by Shimada666** [comment]
> Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

通过局部引入的方式是否有问题？部署又是怎么部署的呢，能提供复现问题的步骤么？

**Comment by tdw143** [comment]
局部引入时，其他页面可以正常使用，会在跳转到有引用到该组件的页面报同样的错

**Comment by Shimada666** [comment]
> 局部引入时，其他页面可以正常使用，会在跳转到有引用到该组件的页面报同样的错

package.json 先提供下？最好能提供下脱敏后的代码方便复现，我好排查问题

**Comment by tdw143** [comment]
![package](https://user-images.githubusercontent.com/82980777/163991900-7bbbba98-6340-49d5-8a01-1939e2be78a8.png)

**Comment by tdw143** [comment]
部署是通过脚本一键部署到服务器的，按理说打包没出错应该不会报错，但它就是报了。。。所以就很没有头绪

**Comment by Shimada666** [comment]
> ![package](https://user-images.githubusercontent.com/82980777/163991900-7bbbba98-6340-49d5-8a01-1939e2be78a8.png)

文字版有么？我复制下来试下

**Comment by tdw143** [comment]
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite --mode development",
    "pro": "vite --mode production",
    "devbuild": "vue-tsc --noEmit && vite build --mode development",
    "probuild": "vue-tsc --noEmit && vite build --mode production",
    "serve": "vite preview"
  },
  "dependencies": {
    "@element-plus/icons": "^0.0.11",
    "@element-plus/icons-vue": "^0.2.7",
    "axios": "^0.24.0",
    "echarts": "^5.2.2",
    "element-plus": "1.3.0-beta.5",
    "is-mobile": "^3.0.0",
    "js-cookie": "^3.0.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "v-code-diff": "^0.3.10",
    "vue": "^3.2.21",
    "vue-echarts": "^6.0.0",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@types/js-cookie": "^3.0.1",
    "@types/lodash": "^4.14.178",
    "@types/node": "^17.0.8",
    "@vitejs/plugin-vue": "^2.0.1",
    "rollup-plugin-external-globals": "^0.6.1",
    "sass": "^1.48.0",
    "vite": "^2.7.10",
    "vite-plugin-cdn-import": "0.3.5",
    "vite-plugin-vue-setup-extend": "^0.4.0"
  }
}

**Comment by tdw143** [comment]
> 你这个 package.json 中甚至都没有装 vue-tsc，而 build 命令中却用到了 vue-tsc，这是怎么打包的？你服务器上打包 vue-tsc 用的是全局的？

是的全局安装的，要在里面安装吗

**Comment by Shimada666** [comment]
> > 你这个 package.json 中甚至都没有装 vue-tsc，而 build 命令中却用到了 vue-tsc，这是怎么打包的？你服务器上打包 vue-tsc 用的是全局的？
> 
> 是的全局安装的，要在里面安装吗

全局装不是一个好的方式。依赖建议放在自己 package.json 里。你这个项目看着是 ts 项目，package.json 中却缺少 vue-tsc 与 typescript 两个依赖，我很疑惑你是怎么跑起来的，你可以加入这两个依赖后再试下，ts 版本依你项目 ts 自定
```json
    "vue-tsc": "^0.3.0",
    "typescript": "^4.4.2"
```

**Comment by Shimada666** [comment]
> > 你这个 package.json 中甚至都没有装 vue-tsc，而 build 命令中却用到了 vue-tsc，这是怎么打包的？你服务器上打包 vue-tsc 用的是全局的？
> 
> 是的全局安装的，要在里面安装吗

另外，你在本地上打包运行也有是有问题的么

**Comment by tdw143** [comment]
![微信截图_20220419195354](https://user-images.githubusercontent.com/82980777/163997696-697cdb53-e246-46ed-a35b-075cd66f0ace.png)
试了下，还是报同样的错

**Comment by tdw143** [comment]
> > > 你这个 package.json 中甚至都没有装 vue-tsc，而 build 命令中却用到了 vue-tsc，这是怎么打包的？你服务器上打包 vue-tsc 用的是全局的？
> > 
> > 
> > 是的全局安装的，要在里面安装吗
> 
> 另外，你在本地上打包运行也有是有问题的么

就是奇怪在这里，本地没问题

**Comment by Shimada666** [comment]
> ![微信截图_20220419195354](https://user-images.githubusercontent.com/82980777/163997696-697cdb53-e246-46ed-a35b-075cd66f0ace.png) 试了下，还是报同样的错

本地没问题，指的是 vite serve 没问题，还是 vite dev 没问题

**Comment by tdw143** [comment]
dev没问题，之前没用过serve，刚试了下也有同样的问题

**Comment by Shimada666** [comment]
> dev没问题，之前没用过serve，刚试了下也有同样的问题

那只能分析具体代码了。可以把你代码发我或者给我一个可复现的仓库。我按你的package.json + 我本地的代码测试是没这个问题的。

**Comment by tdw143** [comment]
> > dev没问题，之前没用过serve，刚试了下也有同样的问题
> 
> 那只能分析具体代码了。可以把你代码发我或者给我一个可复现的仓库。我按你的package.json + 我本地的代码测试是没这个问题的。

已发送邮件给您

**Comment by Shimada666** [comment]
这块初步判断是和你 vite.config.ts 中 importToCDN 冲突了，具体的还需要看下原因

**Comment by tdw143** [comment]
> 这块初步判断是和你 vite.config.ts 中 importToCDN 冲突了，具体的还需要看下原因

大佬，太牛了

**Comment by Shimada666** [comment]
> > 这块初步判断是和你 vite.config.ts 中 importToCDN 冲突了，具体的还需要看下原因
> 
> 大佬，太牛了

解决冲突有以下方案：
1. 依赖中添加 vue-demi
```json
"vue-demi": "^0.12.5",
```
2. vite.config.ts 中，在 autoComplete('vue') 后添加 vue-demi 的 cdn
```typescript
autoComplete('vue'), // 这后面加入 vue-demi cdn
{
   name: 'vue-demi',
   var: 'VueDemi',
   path: "dist/vue_demi.min.js"
}
```

参考：MMF-FE/vite-plugin-cdn-import#13

**Comment by tdw143** [comment]
大佬，再问一下，这个支持自动换行吗

**Comment by Shimada666** [comment]
> 大佬，再问一下，这个支持自动换行吗

还不支持...预计开发的 1.0 版本会支持，但是现在还不支持

**Comment by tdw143** [comment]
十分感谢
