### ISSUE TITLE
使用react时会报错

### ISSUE THREAD

**Issue by MateoLu** [Shimada666/v-code-diff#25]
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/50916752/164213684-1be838f7-bc9e-4bcf-87db-a2c7811b8d41.png">

**Comment by Shimada666** [comment]
呃...这是 vue 插件

**Comment by Shimada666** [comment]
如果你是 vue，react 混搭且使用 cdn，那么 #24 获取可以给你提供帮助

**Comment by MateoLu** [comment]
> 
看了，但不明白什么意思

**Comment by Shimada666** [comment]
> > 
> 
> 看了，但不明白什么意思

如果你也用了 cdn，参照 #24 处理
如果没用，请你提供一个可复现的仓库。
