### ISSUE TITLE
完全一致的情况下显示源码 可以把头部的那个 without change oldstring   without change newString去掉吗

### ISSUE THREAD

**Issue by yangzhen1234** [Shimada666/v-code-diff#26]

**Comment by Shimada666** [comment]
可以，这个是继承了 vue-code-diff 的功能，下个版本我考虑默认隐藏此项，仅显示源码

**Comment by yangzhen1234** [comment]
多谢多谢 请问下个版本什么时候可以用

**Comment by Shimada666** [comment]
就这两天把

**Comment by yangzhen1234** [comment]
多谢大佬，还有刚刚使用的时候发现一个问题  当数据量很大的时候 渲染前的钩子函数和渲染后的钩子函数调用中间差三十四秒，而且渲染前滑动一会 会出现卡死的现象而且操作不了dom，渲染后可以正常滑动正常操作dom 这个是什么问题，大佬能帮忙看下吗
