### ISSUE TITLE
加载大概有一万行数据 这时候会非常卡(使用的是不高亮)，滑动很久才反应 这个可以优化吗

### ISSUE THREAD

**Issue by yangzhen1234** [Shimada666/v-code-diff#27]

**Comment by Shimada666** [comment]
如果是页面渲染过多行数据的话，确实是存在性能问题，得做 vitrual scroll...但是 CodeDiff 这个插件并没有做。我们的插件也只是把这个数据渲染出来，卡确实也正常，也许可以看下 monaco 等插件，表现应该会好点

**Comment by yangzhen1234** [comment]
好的 多谢

**Comment by yangzhen1234** [comment]
这个插件虚拟滚动后续会考虑做吗

**Comment by Shimada666** [comment]
> 这个插件虚拟滚动后续会考虑做吗

这是会的，1.0.0有这个计划但是估计近期无法实现

**Comment by Shimada666** [comment]
现在 1.3.0 优化了这个功能，已经好很多了。实测两个一万行相似的 js 文件 diff 速度已经很快了。一个单一的两万行 json 文件还有点慢，但去掉高亮之后好很多了，欢迎使用
