### ISSUE TITLE
横向滚动条不想让他一起滚动 可以加属性控制吗

### ISSUE THREAD

**Issue by yangzhen1234** [Shimada666/v-code-diff#28]

**Comment by Shimada666** [comment]
0.3.11 先支持了此功能，可以在在线demo试用

**Comment by yangzhen1234** [comment]
您好 我问下哪个属性是控制这个横向滚动的 我在文档上没看到

**Comment by yangzhen1234** [comment]
![image](https://user-images.githubusercontent.com/76575668/166178905-2d8f96b1-c250-4eb9-8df3-70f701b9a459.png)
您好大佬  我项目中使用这个属性 怎么没有用 还是同步滚动的

**Comment by Shimada666** [comment]
> ![image](https://user-images.githubusercontent.com/76575668/166178905-2d8f96b1-c250-4eb9-8df3-70f701b9a459.png) 您好大佬 我项目中使用这个属性 怎么没有用 还是同步滚动的

版本升到最新了么？0.3.11

**Comment by yangzhen1234** [comment]
![image](https://user-images.githubusercontent.com/76575668/166180171-51f446e1-d9e5-439c-9fb8-4fc97c085de5.png)
升级了

**Comment by Shimada666** [comment]
> ![image](https://user-images.githubusercontent.com/76575668/166180171-51f446e1-d9e5-439c-9fb8-4fc97c085de5.png) 升级了

代码确实有问题，这个晚点修复后重新发布

**Comment by yangzhen1234** [comment]
您好 这个前两天可以了 现在又不行了 还是一起滚动了

**Comment by yangzhen1234** [comment]
这个不想让他横向滚动的这个问题有解决吗

**Comment by Shimada666** [comment]
> 这个不想让他横向滚动的这个问题有解决吗

有。。这周我出个新版本，你直接用新版本就不用滚动了

**Comment by yangzhen1234** [comment]
好的 多谢大佬，还是可以通过属性来控制的吗，现在这边需求是用户来控制是否要横向滚动

**Comment by Shimada666** [comment]
> 好的 多谢大佬，还是可以通过属性来控制的吗，现在这边需求是用户来控制是否要横向滚动

不是。。是直接取消了横向滚动的设计。现在会像 github pr 一样在同一行展示了

**Comment by yangzhen1234** [comment]
可以做成那种加属性控制的吗

**Comment by Shimada666** [comment]
短期估计不会。长条根据反应用户不好阅读。像 Github PR 也不提供这样的功能，所以打算是直接取消掉了

**Comment by Shimada666** [comment]
现在出的新版是支持了设置 maxHeight 属性控制组件高度，但是横向滚动条短期内应该不会再支持了
