### ISSUE TITLE
一行中的文本很长时候，可以换行显示吗

### ISSUE THREAD

**Issue by lmjmt** [Shimada666/v-code-diff#3]
RT

**Comment by Shimada666** [comment]
抱歉，我调研了其他的代码对比工具，如 idea 的 diff，一些其他的 code diff 工具，均是不支持这个功能的。此外换行显示，多行在 diff 下如何显示？我感觉这也是一个问题。所以可能并不会支持这个功能

**Comment by lmjmt** [comment]
> 抱歉，我调研了其他的代码对比工具，如 idea 的 diff，一些其他的 code diff 工具，均是不支持这个功能的。此外换行显示，多行在 diff 下如何显示？我感觉这也是一个问题。所以可能并不会支持这个功能

那比较的是json  数据呢，请问能显示json格式化后的对比效果吗
![image](https://user-images.githubusercontent.com/16934473/131462018-48a2a602-19a8-4f43-a7ca-4918d89dd687.png)

**Comment by Shimada666** [comment]
> > 抱歉，我调研了其他的代码对比工具，如 idea 的 diff，一些其他的 code diff 工具，均是不支持这个功能的。此外换行显示，多行在 diff 下如何显示？我感觉这也是一个问题。所以可能并不会支持这个功能
> 
> 那比较的是json 数据呢，请问能显示json格式化后的对比效果吗
> ![image](https://user-images.githubusercontent.com/16934473/131462018-48a2a602-19a8-4f43-a7ca-4918d89dd687.png)

这个功能我建议是，确定输入是 json 数据的时候，格式化后再传入 diff 工具
在这里我提供一个 js 的示例代码

```javascript
const foo = { a: 1, b: 2 }
const formattedJson = JSON.stringify(foo, null, 2)
```

显示效果
```json
{
  "a": 1,
  "b": 2
}
```

**Comment by lmjmt** [comment]
明白了，谢谢
