### ISSUE TITLE
vue3单独引入的时候页面会报错，

### ISSUE THREAD

**Issue by Jankos-li** [Shimada666/v-code-diff#30]
export default {
  name: 'App',
  components: {
    CodeDiff
  }

**Comment by Shimada666** [comment]
请贴出详细的报错截图，以及代码

**Comment by Jankos-li** [comment]
这段代码是放在script里面的，因为页面会报错，我就将其注释掉了，
![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png)
这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。
![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)

**Comment by Jankos-li** [comment]
因为现在不在公司，不能启动项目，所以报错截图我没粘上去，不注释的话页面打不开。

**Comment by Shimada666** [comment]
> 这段代码是放在script里面的，因为页面会报错，我就将其注释掉了， ![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png) 这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。 ![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)

你代码没贴全，看起来是用 vue3 + setup script 语法，那么仅需在 script 标签中加入
```javascript
 import { CodeDiff } from 'v-code-diff' 
```
这一条应该就可以已正常使用了

**Comment by Jankos-li** [comment]
> > 这段代码是放在script里面的，因为页面会报错，我就将其注释掉了， ![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png) 这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。 ![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)
> 
> 你代码没贴全，看起来是用 vue3 + setup script 语法，那么仅需在 script 标签中加入
> 
> ```js
>  import { CodeDiff } from 'v-code-diff' 
> ```
> 
> 这一条应该就可以已正常使用了

这个我加了，意思是不需要加入export import啥的是吧。

**Comment by Shimada666** [comment]
> > > 这段代码是放在script里面的，因为页面会报错，我就将其注释掉了， ![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png) 这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。 ![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)
> > 
> > 
> > 你代码没贴全，看起来是用 vue3 + setup script 语法，那么仅需在 script 标签中加入
> > ```js
> >  import { CodeDiff } from 'v-code-diff' 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这一条应该就可以已正常使用了
> 
> 这个我加了，意思是不需要加入export import啥的是吧。

那一段是示例，export import 是 vue 的使用方法，但是你错误的直接复制进去了

**Comment by Jankos-li** [comment]
> > > > 这段代码是放在script里面的，因为页面会报错，我就将其注释掉了， ![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png) 这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。 ![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)
> > > 
> > > 
> > > 你代码没贴全，看起来是用 vue3 + setup script 语法，那么仅需在 script 标签中加入
> > > ```js
> > >  import { CodeDiff } from 'v-code-diff' 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这一条应该就可以已正常使用了
> > 
> > 
> > 这个我加了，意思是不需要加入export import啥的是吧。
> 
> 那一段是示例，export import 是 vue 的使用方法，但是你错误的直接复制进去了

现在有效果了，但是数据都汇总在一行是为啥呢？按理不是应该遇到逗号换行吗？
![image](https://user-images.githubusercontent.com/76777318/168709848-799e706e-72b3-42f7-b653-659ceedb8954.png)

**Comment by Shimada666** [comment]
> > > > > 这段代码是放在script里面的，因为页面会报错，我就将其注释掉了， ![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png) 这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。 ![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)
> > > > 
> > > > 
> > > > 你代码没贴全，看起来是用 vue3 + setup script 语法，那么仅需在 script 标签中加入
> > > > ```js
> > > >  import { CodeDiff } from 'v-code-diff' 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这一条应该就可以已正常使用了
> > > 
> > > 
> > > 这个我加了，意思是不需要加入export import啥的是吧。
> > 
> > 
> > 那一段是示例，export import 是 vue 的使用方法，但是你错误的直接复制进去了
> 
> 现在有效果了，但是数据都汇总在一行是为啥呢？按理不是应该遇到逗号换行吗？ ![image](https://user-images.githubusercontent.com/76777318/168709848-799e706e-72b3-42f7-b653-659ceedb8954.png)

怎么可能按逗号换行呢，是按换行符换行

**Comment by Jankos-li** [comment]
> > > > > > 这段代码是放在script里面的，因为页面会报错，我就将其注释掉了， ![image](https://user-images.githubusercontent.com/76777318/168579660-be810c98-00dc-490f-93dc-a8a455a8b04f.png) 这个是我的使用，是放在一个el-dialog标签中，rowdata.value.oldconstant是我的数据源。 ![image](https://user-images.githubusercontent.com/76777318/168579826-06cb8f27-9e96-4d93-b0f4-f04679e25b2b.png)
> > > > > 
> > > > > 
> > > > > 你代码没贴全，看起来是用 vue3 + setup script 语法，那么仅需在 script 标签中加入
> > > > > ```js
> > > > >  import { CodeDiff } from 'v-code-diff' 
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 这一条应该就可以已正常使用了
> > > > 
> > > > 
> > > > 这个我加了，意思是不需要加入export import啥的是吧。
> > > 
> > > 
> > > 那一段是示例，export import 是 vue 的使用方法，但是你错误的直接复制进去了
> > 
> > 
> > 现在有效果了，但是数据都汇总在一行是为啥呢？按理不是应该遇到逗号换行吗？ ![image](https://user-images.githubusercontent.com/76777318/168709848-799e706e-72b3-42f7-b653-659ceedb8954.png)
> 
> 怎么可能按逗号换行呢，是按换行符换行

哈哈哈是的，已经解决了，刚想回复您来着，多谢！
