### ISSUE TITLE
有些文件对比左右会错位

### ISSUE THREAD

**Issue by yangzhen1234** [Shimada666/v-code-diff#32]
![image](https://user-images.githubusercontent.com/76575668/170401071-17e9a6c4-4755-4d4e-b909-28588619da91.png)
![image](https://user-images.githubusercontent.com/76575668/170401105-1aebf424-3fb6-447c-ad55-998b56ed8eed.png)
这种展示出来左右是错位的是什么原因
左侧数据：
{
    "code": 0,
    "data": [
        "2022-05-18 16:02:30",
        "2022-05-18 16:02:31",
        "2022-05-18 16:02:32",
        "2022-05-18 16:02:33",
        "2022-05-18 16:02:34",
        "2022-05-18 16:02:35",
        "2022-05-18 16:02:36",
        "2022-05-18 16:02:37",
        "2022-05-18 16:02:38",
        "2022-05-18 16:02:39"
    ],
    "msg": "操作成功"
}
右侧数据：
{
    "code": 0,
    "data": [
        "2022-05-18 18:04:37",
        "2022-05-24 18:04:38",
        "2022-05-24 18:04:39",
        "2022-05-24 18:04:40",
        "2022-05-24 18:04:41",
        "2022-05-24 18:04:42",
        "2022-05-24 18:04:43",
        "2022-05-24 18:04:44",
        "2022-05-24 18:04:45",
        "2022-05-24 18:04:46"
    ],
    "msg": "操作成功"
}

**Comment by Shimada666** [comment]
符合预期，他并不是逐行比对的。通过 diff 算法算出来的就是这样，包括其他的对比器，应该也是类似的操作
