### ISSUE TITLE
properties文件比对时，如果第一行为注释，且没有差异，那么插件会自动忽略第一行

### ISSUE THREAD

**Issue by codingLemonzz** [Shimada666/v-code-diff#36]
在properties类型文件内容进行对比时发现，如果第一行为注释，且对比内容没有差异的时候，第一行注释会不显示，希望可以修复一下。
原始数据：
![image](https://user-images.githubusercontent.com/35480636/177938555-12071b0c-2488-4f7d-a1b9-ef0f1cc1d881.png)
展示出来的数据：
![image](https://user-images.githubusercontent.com/35480636/177938616-4277eec2-fe85-4b3f-a57a-cad756e4eef7.png)

**Comment by Shimada666** [comment]
这个是数据有差异，而且上下代码行数设置了 10，备注刚好在 10 行之外，如果希望展示所有，可以把 context 设置为一个比较大的值，比如 9999。后续可能会增加点击展开的功能

**Comment by codingLemonzz** [comment]
> 
问题解决了，感谢！~
