### ISSUE TITLE
字符串对比有不同的上面没有标深红，能帮忙看下吗

### ISSUE THREAD

**Issue by yangzhen1234** [Shimada666/v-code-diff#37]
![image](https://user-images.githubusercontent.com/76575668/179441587-b144163e-1225-4d63-8a64-08307ca3fbdd.png)
上面字符串："recordResponse": "{\"code\":\"200\",\"data\":{\"createTime\":\"2022-05-11 14:40:10\",\"createUserName\":\"赵铁军\",\"createUserNo\":\"80037\",\"employeeNo\":\"80037\",\"idCard\":\"211221198110152419\",\"modifiedTime\":\"2022-05-11 14:40:12\",\"modifiedUserNo\":\"80037\",\"status\":\"2\",\"submitTime\":\"2022-05-11 14:40:12\",\"submitUserName\":\"赵铁军\",\"submitUserNo\":\"80037\",\"weeklyId\":\"553007\",\"workDate\":\"2022-05-11 00:00:00\",\"workDay\":\"周三\",\"workDayId\":\"2182485\",\"workTotal\":8.0},\"msg\":\"提交成功\",\"success\":true}",
下面字符串："recordResponse": "{\"code\":\"200\",\"data\":{\"createTime\":\"2022-05-11 14:40:10\",\"createUserName\":\"赵铁军\",\"createUserNo\":\"80037\",\"employeeNo\":\"80037\",\"idCard\":\"211221198110152419\",\"modifiedTime\":\"2022-05-11 14:40:12\",\"modifiedUserName\":null,\"modifiedUserNo\":\"80037\",\"status\":\"2\",\"submitTime\":\"2022-05-11 14:40:12\",\"submitUserName\":\"赵铁军\",\"submitUserNo\":\"80037\",\"\"80037\",\"status\":\"2\",\"submitTime\":\"2022-05-11 14:40:12\",\"submitUserName\":\"赵铁军\",\"submitUserNo\":\"80037\",\"weeklyDayDetail\":null,\"weeklyId\":\"553007\",\"workDate\":\"2022-05-11 00:00:00\",\"workDay\":\"周三\",\"workDayId\":\"2182485\",\"workTotal\":8.0},\"msg\":\"提交成功\",\"success\":true}",\"553007\",\"workDate\":\"2022-05-11 00:00:00\",\"workDay\":\"周三\",\"workDayId\":\"2182485\",\"workTotal\":8.0},\"msg\":\"提交成功\",\"success\":true}",

**Comment by Shimada666** [comment]
是不是设置了 prop：language，是的话，这应该是个 bug

**Comment by Shimada666** [comment]
现在出了 1.0.0 版本了，可以考虑下最新版本
