### ISSUE TITLE
请问支持点击展开折叠内容吗

### ISSUE THREAD

**Issue by jiayan0520** [Shimada666/v-code-diff#4]
请问支持展开折叠的内容吗？就是默认是折叠，点击折叠地方可以展开，类似github merge代码

**Comment by Shimada666** [comment]
> 请问支持展开折叠的内容吗？就是默认是折叠，点击折叠地方可以展开，类似github merge代码

请问指的是github pr里每个文件右上角的viewed按钮，还是说默认折叠的那些没有变化的代码，点击后可以显示呢

**Comment by jiayan0520** [comment]
默认折叠的那些没有变化的代码，点击后可以显示

**Comment by Shimada666** [comment]
> 默认折叠的那些没有变化的代码，点击后可以显示

暂时还没做好支持，这个是diff2html的限制，他没有做这块的支持。我计划后期自己渲染html，来添加这个功能，但是这需要一定时间，短期可能无法实现

**Comment by lz-happy** [comment]
> 默认折叠的那些没有变化的代码，点击后可以显示

请问有找到比较好的解决方案吗

**Comment by tffff** [comment]
这个功能有后续吗？

**Comment by Shimada666** [comment]
> 这个功能有后续吗？

会开发的..但是最近时间不是很充足

**Comment by Shimada666** [comment]
@jiayan0520 @tffff @lz-happy 

此功能已由 @cjboy76 开发，可以安装 1.5.0 版本试用。感谢 cjboy76 的付出！
This feature has been developed by @cjboy76 and can be tried by installing version 1.5.0. Thanks for cjboy76's contributon!
