### ISSUE TITLE
vue2 使用问题

### ISSUE THREAD

**Issue by zkyCarry** [Shimada666/v-code-diff#44]
ERROR in /Users/momoQuasar/spacey/node_modules/v-code-diff/dist/v-code-diff/v-code-diff.d.ts(3,44):
TS2694: Namespace '"/Users/momoQuasar/spacey/node_modules/vue-demi/lib/index"' has no exported member 'DefineComponent'.
Version: typescript 4.2.2, eslint 7.32.0
Time: 3928 ms

**Comment by Shimada666** [comment]
像是 typescript 问题，考虑采用下全局引入的方式看看能不能解决问题
