### ISSUE TITLE
关于无差异比对的一点疑问

### ISSUE THREAD

**Issue by doublebit015** [Shimada666/v-code-diff#46]
问题：在使用比对功能时，对于无差异的场景，会额外多一行 File Without Change 的文本。
需求：因为没有差异的文本也需要看到内容（isShowNoChange设置为true），又不想要有 File Without Change 这一行（这有可能会让用户端认为这段代码存在差异）
疑问：我在vue-code-diff上使用的话，无差异比对是不会多出这一行的。我down了代码下来看，发现这一行文本是主动赋值上去的，请问这样做是因为现有方案不支持这种场景嘛，还是有什么其他考量

**Comment by Shimada666** [comment]
确实是现有代码不支持此场景...因为现在逻辑是直接使用 diff2html 进行比对，不加这一行就无法比对。新版改为自行实现 diff 逻辑，去掉了此依赖，所以可以支持这种场景，但是最近比较忙，新版一些问题解决后才能发布，我可以到时候发布后回复你

**Comment by doublebit015** [comment]
> 确实是现有代码不支持此场景...因为现在逻辑是直接使用 diff2html 进行比对，不加这一行就无法比对。新版改为自行实现 diff 逻辑，去掉了此依赖，所以可以支持这种场景，但是最近比较忙，新版一些问题解决后才能发布，我可以到时候发布后回复你

理解，期待早日体验到新特性 😄

**Comment by Shimada666** [comment]
> > 确实是现有代码不支持此场景...因为现在逻辑是直接使用 diff2html 进行比对，不加这一行就无法比对。新版改为自行实现 diff 逻辑，去掉了此依赖，所以可以支持这种场景，但是最近比较忙，新版一些问题解决后才能发布，我可以到时候发布后回复你
> 
> 理解，期待早日体验到新特性 😄

新版本现已支持，当数据无变化时直接展示
