### ISSUE TITLE
ie11报 script1010: 缺少标识符

### ISSUE THREAD

**Issue by 695813758** [Shimada666/v-code-diff#49]
把咱这个插件注释掉就可以进页面啦,  点击报错标识定位到了 (...e),      网上查了一下一般是使用了保留关键词 或者 json结尾有逗号,  去代码里没有定位到,   求大佬赐教

**Comment by Shimada666** [comment]
确实没测试过 ie 的兼容性，我后面找个 ie 测试下

**Comment by 695813758** [comment]
> 确实没测试过 ie 的兼容性，我后面找个 ie 测试下

大佬费心了,  谢谢

**Comment by Shimada666** [comment]
确实是不支持 ie11 的，我想都能用上代码对比功能的...应该不会有人用 ie11 吧
