### ISSUE TITLE
关于文件头部的建议和优化

### ISSUE THREAD

**Issue by ZhangTomLiang** [Shimada666/v-code-diff#56]
1.当不传filename的时候，是否可以支持头部不展示
2.关于新增和修改的条数那块，是否暴露出一个作用域插槽，支持自定义样式

以上是实际使用中出现的问题，可能是个例，望大佬参考参考.

**Comment by Shimada666** [comment]
1.比较容易支持，事实上我也没想好默认展示还是不展示好
2.你们的场景中 暴露个 slot 出来，你们一般会自定义哪些内容呢？新增和删除的条数是内部状态，组件使用者还不太好获取内部状态来自定义一些内容

**Comment by ZhangTomLiang** [comment]
其实我这边只需要修改那块的样式，比如新增1条，删除1条等...

**Comment by Shimada666** [comment]
> 其实我这边只需要修改那块的样式，比如新增1条，删除1条等...

那其实也得获取到具体的对比结果的统计信息才行..

**Comment by ZhangTomLiang** [comment]
如果这块不好优化，我就隐藏吧
