### ISSUE TITLE
末尾换行符不同能忽略吗？

### ISSUE THREAD

**Issue by HelloYLee** [Shimada666/v-code-diff#6]
现在新增一行，前一行没有修改也会显示出来，应该是行末换行符的问题？

**Comment by Shimada666** [comment]
是的，我考虑出个 prop 配置后可以比较 trim 掉的内容。

**Comment by Shimada666** [comment]
0.3.4 版本支持此功能，使用 prop `trim`

**Comment by HelloYLee** [comment]
![image](https://user-images.githubusercontent.com/43162757/133361374-a6bac614-3646-401b-a73e-ab11814a1e76.png)

加了trim 还是不行

**Comment by Shimada666** [comment]
> ![image](https://user-images.githubusercontent.com/43162757/133361374-a6bac614-3646-401b-a73e-ab11814a1e76.png)
> 
> 加了trim 还是不行

这是符合预期的。这里trim只是trim掉字符串头尾的空白字符。而你这个换行符是在两行之间的，是没办法 trim 掉的

**Comment by HelloYLee** [comment]
> > ![image](https://user-images.githubusercontent.com/43162757/133361374-a6bac614-3646-401b-a73e-ab11814a1e76.png)
> > 加了trim 还是不行
> 
> 这是符合预期的。这里trim只是trim掉字符串头尾的空白字符。而你这个换行符是在两行之间的，是没办法 trim 掉的


对的，但是我这个一开始说的应该就是换行符的问题。我看beyond compare，这个换行符是忽略的

**Comment by Shimada666** [comment]
> > > ![image](https://user-images.githubusercontent.com/43162757/133361374-a6bac614-3646-401b-a73e-ab11814a1e76.png)
> > > 加了trim 还是不行
> > 
> > 
> > 这是符合预期的。这里trim只是trim掉字符串头尾的空白字符。而你这个换行符是在两行之间的，是没办法 trim 掉的
> 
> 对的，但是我这个一开始说的应该就是换行符的问题。我看beyond compare，这个换行符是忽略的

这样，我在下个版本中再出个prop，对每一行单独trim
