### ISSUE TITLE
vue2版本，使用官方demo会报 Cannot read properties of undefined (reading 'diffChange')

### ISSUE THREAD

**Issue by Maginaaa** [Shimada666/v-code-diff#60]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/19279437/230584308-d283a389-450b-41ec-89cc-5b65cfa6dbf1.png">

![image](https://user-images.githubusercontent.com/19279437/230584475-69ffb8fa-5101-4dd6-8b9c-b4688fc7553d.png)

**Comment by Shimada666** [comment]
插件和 vue 是什么版本的？
视图能正常渲染吗？

**Comment by Maginaaa** [comment]
视图也无法渲染
<img width="286" alt="image" src="https://user-images.githubusercontent.com/19279437/230587934-04463ed0-4a0c-414b-b264-450cd662caa0.png">

**Comment by Maginaaa** [comment]
我在相同环境下，把v-code-diff的版本降到原来使用过的0.3.11版本，这个问题就好了

**Comment by Shimada666** [comment]
> 我在相同环境下，把v-code-diff的版本降到原来使用过的0.3.11版本，这个问题就好了

那你可以试下删除整个 node_modules 和你的 lock 文件，重新安装一下依赖，估计新版本也是正常的。
新版本在高亮、大文本处理上都远强于旧版本，是比较推荐的

**Comment by Maginaaa** [comment]
我就是启的新项目，重新装的环境，用最新版本v-code-diff碰到的这个问题

**Comment by Maginaaa** [comment]
晚点我试下，弄个新容器起个demo，再使用新版本看能不能复现

**Comment by adamibai** [comment]
我在vue2.6.14也出现了一样的情况，vue版本降到2.6.12就没有了，还有其他解决方法吗

**Comment by Shimada666** [comment]
> 我在vue2.6.14也出现了一样的情况，vue版本降到2.6.12就没有了，还有其他解决方法吗

<img width="477" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/1694d8b0-9da8-4c3b-a62a-2b84502bd3af">
<img width="721" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/ed14ea31-e015-402a-b6ff-0ac2412275ab">


个人测试 vue2.6.14 不会出现此情况，可以提供最小可复现仓库看一下

**Comment by Shimada666** [comment]
今天有人遇到了这个问题，帮助排查了一下，发现是 oldString 或 newString 传入了 undefined 所致，诸位可以测试一下是否是此情况导致的。
