### ISSUE TITLE
Clicking the Expand button does nothing.

### ISSUE THREAD

**Issue by JoelYoung01** [Shimada666/v-code-diff#61]
Hello, I have been playing with this neat package and have noticed that when there are breaks in the compare due to large enough areas that don't have any changes, it will collapse the lines and instead show a summary line. This is nice, however when I go to click the summary line to expand the unchanged code, nothing happens.

This can be recreated by going to [the demo site](https://shimada666.github.io/v-code-diff/) and setting the 'context' to 1:
![image](https://user-images.githubusercontent.com/90867915/230928535-2cc7163a-15ee-421c-95f3-41ba9986627d.png)

You will see the code collapses down as expected. However, when trying to reveal the collapsed code, nothing happens.
Specifically, I would expect clicking the blue areas pictured below would expand the hidden lines.
![image](https://user-images.githubusercontent.com/90867915/230928774-1f89de53-b659-4d70-9b88-31a93ceedafa.png)

**Comment by Shimada666** [comment]
Yes, the expected behavior here is to expand the code upon clicking, but this functionality has not been implemented yet. I have been quite busy recently, but I will work on implementing it in the future. However, it may take some time, so I apologize for any inconvenience this may cause. I will do my best to find the time to improve it.

**Comment by cjboy76** [comment]
@Shimada666 Hello, I think I can help with this feature.

**Comment by Shimada666** [comment]
> @Shimada666 Hello, I think I can help with this feature.

Sounds good! Could you please create a PR? To be honest, I'm a little busy recently..

**Comment by Shimada666** [comment]
@JoelYoung01 
This feature has been developed by @cjboy76 and can be tried by installing version 1.5.0. Thanks for cjboy76's contributon!
