### ISSUE TITLE
老项目catch不加参数会报错，webpack版本太低babel没法升级，可以辛苦作者改下吗，我本地打补丁但是在ci上没有权限更改文件

### ISSUE THREAD

**Issue by cyaj** [Shimada666/v-code-diff#62]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `v-code-diff@1.3.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/v-code-diff/dist/index.es.js b/node_modules/v-code-diff/dist/index.es.js
index 40a8bf0..4e86a09 100644
--- a/node_modules/v-code-diff/dist/index.es.js
+++ b/node_modules/v-code-diff/dist/index.es.js
@@ -596,7 +596,7 @@ var ce = {}, Yn = {
         case "+":
           try {
             i[s++] = new n.Diff(u, decodeURI(f));
-          } catch {
+          } catch(err) {
             throw new Error("Illegal escape in diff_fromDelta: " + f);
           }
           break;
@@ -825,7 +825,7 @@ var ce = {}, Yn = {
         var f = i[s].charAt(0);
         try {
           var g = decodeURI(i[s].substring(1));
-        } catch {
+        } catch(err) {
           throw new Error("Illegal escape in patch_fromText: " + g);
         }
         if (f == "-")
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Shimada666** [comment]
老实说我没看懂..
这应该是构建产物，我应该做什么呢

**Comment by cyaj** [comment]
是这样的，我目前维护的项目是基于webpack3版本的vue2老项目，我引入v-code-diff之后报错语法识别不了并给出了行号提示，我根据引入的文件路径，给提示处那一行的catch加了参数（虽然用不到这个参数）解决了报错，然后我打了补丁，本地是没有问题，但是线上ci构建的时候提示无写入权限没法更改文件，所以希望作者辛苦改下这个。这个构建文件index.es.js中还有一处try catch是加了参数的，我猜测是不是作者写的时候没有加，我项目由于webpack版本原因没法升级babel，所以识别不了这种不算错误的写法

**Comment by Shimada666** [comment]
我看你提供的代码，像是 diff 库的，我代码中没有 try catch 逻辑。
现在我不太清楚要怎么做，如果用 legacy 之类的插件可以解决这个问题帮到你，我很乐意修改

**Comment by cyaj** [comment]
hello，我找到了解决方法，在`node_modules`找到`diff-match-patch`，在`index.js`中搜索catch，1382行和2123行这两个try catch 语句有参数但没有使用，这应该是打包之后没参数的原因。只需要拼接上这个参数，打包之后index.es.js中的catch就有参数了
```js
// 1382
try { 
          diffs[diffsLength++] =
              new diff_match_patch.Diff(DIFF_INSERT, decodeURI(param));
        } catch (ex) {
          // Malformed URI sequence.
          throw new Error('Illegal escape in diff_fromDelta: ' + param + ex);
        }
// 2123
 try { 
        var line = decodeURI(text[textPointer].substring(1));
      } catch (ex) {
        // Malformed URI sequence.
        throw new Error('Illegal escape in patch_fromText: ' + line + ex);
      }
```

**Comment by cyaj** [comment]
然后发布就可以了，我自己发布了一个测试，是ok的

**Comment by Shimada666** [comment]
你的意思是打包后再去改 index.es.js.. 然后发布修改后的版本吗.. 
这可能有点过于 trick 了，我估计不会做这样的改动，但是你可以 fork 一个然后修改后发布到你们公司自己的 npm 源上。如果有更好的办法，欢迎告诉我

**Comment by cyaj** [comment]
不是打包后修改index.es.js，这样没用的因为发布会重新打包。
我上面的代码是修改node_modules中diff-match-patch里的index.js，然后正常打包发布就OK了
