### ISSUE TITLE
怎么获取该文件的比对差异数量

### ISSUE THREAD

**Issue by Charlottehy** [Shimada666/v-code-diff#65]
怎么获取该文件的比对差异数，比如新增数多少，删减数量多少这两参数值呢？

**Comment by Shimada666** [comment]
目前没有暴露出来，有这个需求的话我考虑用emit或者ref之类的暴露出来

**Comment by Charlottehy** [comment]
我觉得阔以...，大佬你啥时候加呀

**Comment by Shimada666** [comment]
我看看吧，有空的时候看一下怎么实现比较方便，好了通知你哈

**Comment by Charlottehy** [comment]
好哒，蟹蟹大神~

**Comment by Shimada666** [comment]
感谢 @09473ZH 的 pr(#82)，现在已经有了，diff 事件可以获取是否变更、添加行数、删除行数
