### ISSUE TITLE
你好想问一下，gitlab接口返回的数据直接是diff差异好的数据，没有原数据与新数据比较，用什么组件适用

### ISSUE THREAD

**Issue by chen-ctrl** [Shimada666/v-code-diff#66]
返回的数据形式
"diff": "@@ -10,7 +10,29 @@ import org.springframework.stereotype.Service;\n import [java.util.Date](http://link.zhihu.com/?target=http%3A//java.util.Date);\n \n @Service\n-public class UserServiceImpl implements UserService {\n+public class UserTestServiceImpl implements UserService {\n+\n+ @Autowired\n+ private UserMapper userMapper;\n+\n+ @Override\n+ public User getInfo() {\n+ Integer userId = ShiroUtil.getCurrUserIdNotNull();\n+ User user = userMapper.selectById(userId);\n+ return user;\n+ }\n+\n+ @Override\n+ public Boolean updateInfo(User user) {\n+ Integer userId = ShiroUtil.getCurrUserIdNotNull();\n+ user.setId(userId);\n+ user.setUpdateDate(new Date());\n+ if(user.updateById()){\n+ return true;\n+ }\n+ return false;\n+ }\n+\n \n @Autowired\n private UserMapper userMapper;\n",

**Comment by Shimada666** [comment]
可以使用 diff2html 实现
