### ISSUE TITLE
vue2  0.3.4版本有bug

### ISSUE THREAD

**Issue by HelloYLee** [Shimada666/v-code-diff#7]
![image](https://user-images.githubusercontent.com/43162757/133013111-e7695416-a2e5-40c0-a42f-b569fa5fb540.png)

**Comment by Shimada666** [comment]
我似乎没有问题，能麻烦提供一个复现问题的最小仓库吗

**Comment by HelloYLee** [comment]
没太懂。我之前用的是0.3.3 版本，因为想用新功能所以升级的0.3.4，但是调用运行之后console报这个错误

**Comment by Shimada666** [comment]
> 没太懂。我之前用的是0.3.3 版本，因为想用新功能所以升级的0.3.4，但是调用运行之后console报这个错误

能否贴一下你的 package.json？可以的话最好能提供一个能复现bug的项目

**Comment by HelloYLee** [comment]
package.json需要哪些项的参数？

**Comment by Shimada666** [comment]
> package.json需要哪些项的参数？

至少要有 dependencies, devDependencies

**Comment by Shimada666** [comment]
这个是否还有问题？没有问题我关了

**Comment by HelloYLee** [comment]
> 这个是否还有问题？没有问题我关了
没再出现了，你关吧

**Comment by HelloYLee** [comment]
> 这个是否还有问题？没有问题我关了


没有出现了，你关吧
