### ISSUE TITLE
引入后报错，项目不能访问

### ISSUE THREAD

**Issue by colaiven** [Shimada666/v-code-diff#74]
![image](https://github.com/Shimada666/v-code-diff/assets/46585176/fcdb26e6-c6c8-4a10-a4aa-e8e097326403)
暂时还不能找到具体是哪个模块影响了，项目太大了，引入的包也很多，研究了几天了，着实搞不定，麻烦作者大大看看有没有思路，目前只是在我们这一个项目出现了这个问题，其他项目都能正常使用。

**Comment by colaiven** [comment]
![image](https://github.com/Shimada666/v-code-diff/assets/46585176/73573512-664f-42ef-acea-9758449ca201)
报错在这一行，在main.js引入页面就白屏，浏览器就报错，vue版本是2.7.14

**Comment by Shimada666** [comment]
为啥你们会引用到 index.cjs.js 呢？你们是 nodejs 而不是浏览器端项目么？

**Comment by colaiven** [comment]
> 为啥你们会引用到 index.cjs.js 呢？你们是 nodejs 而不是浏览器端项目么？

是浏览器端的

**Comment by colaiven** [comment]
大佬有时间给帮忙看看吗？在下实在是没辙了

**Comment by colaiven** [comment]
![image](https://github.com/Shimada666/v-code-diff/assets/46585176/2362482c-0a23-42f5-98cf-0c5b9c4787de)
这个是在页面上单独引入的情况，也是报同样的，只不过这里变成了警告，但是差异对比这个组件还是不能正常显示

**Comment by Shimada666** [comment]
浏览器端的项目不应该用到 cjs 文件啊，你可以在 vue.config.js 里改一下 resolve，让 CodeDiff 指向 node_modules 下的 index.es.js 试下，不行的话可以给下联系方式或者加我主页 qq 看下
