### ISSUE TITLE
建议比较的页面的加上旧值和新值的标题。

### ISSUE THREAD

**Issue by zpwillbebetter** [Shimada666/v-code-diff#76]
博主你好，建议比较的页面的加上旧值和新值的标题。
![image](https://github.com/Shimada666/v-code-diff/assets/26972394/76a1baa2-b715-4e95-a3d4-f0609e22a7f0)

**Comment by Shimada666** [comment]
目前是有一个 filename 属性，来提供文件名展示，对于不同文件名有需求的话，我后续也跟进支持一下

**Comment by zpwillbebetter** [comment]
感谢。

**Comment by gosszhang** [comment]
+1 我也有个需求

**Comment by Shimada666** [comment]
好的，我们尽快支持这个功能

**Comment by liyoungs** [comment]
+1

**Comment by Shimada666** [comment]
> +1

好的...我们按 idea 的 diff 方式做一个

**Comment by Shimada666** [comment]
1.8.0 已支持
