### ISSUE TITLE
可否让比较后的新值和旧值两块区域可以单独选中复制

### ISSUE THREAD

**Issue by zpwillbebetter** [Shimada666/v-code-diff#77]
博主你好，可否让比较后的新值和旧值两块区域可以单独选中复制。
![image](https://github.com/Shimada666/v-code-diff/assets/26972394/ff6e1816-1824-4a2a-a853-ea12177be42d)

**Comment by Shimada666** [comment]
可以的，这个也在预计支持之中，接下来会排期支持

**Comment by zpwillbebetter** [comment]
感谢。

**Comment by 09473ZH** [comment]
https://github.com/Shimada666/v-code-diff/pull/88

**Comment by Shimada666** [comment]
1.7.0 已支持
