### ISSUE TITLE
当新旧代码diff没有改变时，怎么能知道它没有发生改变呢

### ISSUE THREAD

**Issue by Begratefuliy** [Shimada666/v-code-diff#80]
![image](https://github.com/Shimada666/v-code-diff/assets/71127790/6f3a3e40-c1fc-4b67-918d-088b21cfce70)
当这种没有改变时，想去提示用户

**Comment by Shimada666** [comment]
下个版本我做个 event，diff 完之后触发，告诉用户差异情况（是否产生变化，增加多少，删除多少），当都是 0 时可认为没有变化。你可以依此 event 提示用户

**Comment by Begratefuliy** [comment]
好滴，给你点个赞

**Comment by Begratefuliy** [comment]
希望到时候版本更新的时候，能踢我一下

**Comment by Shimada666** [comment]
> 希望到时候版本更新的时候，能踢我一下

ok，我们尽快

**Comment by Shimada666** [comment]
感谢 @09473ZH 的 pr(#82)，现在已经有了，diff 事件可以获取是否变更、添加行数、删除行数

**Comment by Sajotim** [comment]
感恩
