### ISSUE TITLE
v1.6.0 构建失败：Error: Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by youthug** [Shimada666/v-code-diff#84]
`node:fs` 在 node v18 引入，是否考虑兼容下低版本项目使用 `fs` 来引用？

**Comment by Shimada666** [comment]
> `node:fs` 在 node v18 引入，是否考虑兼容下低版本项目使用 `fs` 来引用？

很有道理，我改为 fs

**Comment by wanggang19** [comment]
> 已修复

老哥顺便把utils.js里面的这个问题也修复下

**Comment by wanggang19** [comment]
> 已修复

![Uploading image.png…]()
两个地方

**Comment by Shimada666** [comment]
> > 已修复
> 
> 老哥顺便把utils.js里面的这个问题也修复下

不好意思，忽略了，eslint 自动格式化的，我修一下

**Comment by Shimada666** [comment]
> > 已修复
> 
> 老哥顺便把utils.js里面的这个问题也修复下

已修复，1.6.2 版本应该可用

**Comment by youthug** [comment]
v1.6.2 验证没问题
