### ISSUE TITLE
请问可以增加指定编码格式的功能（文件里面如果写中文现在没法正常显示）

### ISSUE THREAD

**Issue by LoveELF** [Shimada666/v-code-diff#85]
请问可以增加指定编码格式的功能，或者自动判断（文件里面如果写中文现在没法正常显示）
![image](https://github.com/Shimada666/v-code-diff/assets/635336/3d60fa8d-d8a4-4029-ac7a-4afa6263a090)

**Comment by Shimada666** [comment]
这不是指定编码格式的问题，你可以看下你接口，这一般是你后端直接传了非中文的内容给你。你可以让后端做转换后传给你正常的中文，或者你自行做 unicode 解码后再传入组件
