### ISSUE TITLE
添加新行显示问题

### ISSUE THREAD

**Issue by Horus-K** [Shimada666/v-code-diff#89]
![image](https://github.com/Shimada666/v-code-diff/assets/48319268/1441f8de-c1c7-49f5-b77b-dbbb799f7431)第一行数据完全一样，不是应该只显示1行修改吗
![image](https://github.com/Shimada666/v-code-diff/assets/48319268/c0cc0ef2-bc8d-4ef1-9a6c-3bb228eb5b02)

**Comment by Shimada666** [comment]
其实并不完全一样，右边的第一行多了个换行符

**Comment by Horus-K** [comment]
![image](https://github.com/Shimada666/v-code-diff/assets/48319268/b56d47af-ead3-4013-97cf-4ae4c4d80b93)

原始数据{new: '"wwaxxxx4f1e33c01df" "qywx-svc1";\n"wwxxxxf90528f7c0e-tmp-1" "qywx-svc1";', old: '"wwaxxxx4f1e33c01df" "qywx-svc1";'}
有没有办法显示成这样的

**Comment by Horus-K** [comment]
:noDiffLineFeed=true  这样写不就是忽略换行吗

**Comment by Horus-K** [comment]
确实，先临时加一下吧
