### ISSUE TITLE
vue2里面用不了，报没有componsition-api

### ISSUE THREAD

**Issue by zhoufanglu** [Shimada666/v-code-diff#9]
![image](https://user-images.githubusercontent.com/24451091/134638068-0f39fddf-97ec-4e11-8a9d-110a5df26e9a.png)

**Comment by Shimada666** [comment]
readme 有写，你要先装一下 composition-api

**Comment by zhoufanglu** [comment]
> readme 有写，你要先装一下 composition-api

哦哦 看到了，那在vue2里面不值得用， 谢谢了
