### ISSUE TITLE
增加一个功能：传入一个黑名单，在该黑名单中的字段不管左右是否有差异都不显示高亮效果。感谢大佬

### ISSUE THREAD

**Issue by xiaowanghappyyyyyyyyyyyyyy** [Shimada666/v-code-diff#90]
增加一个功能：传入一个黑名单，在该黑名单中的字段不管左右是否有差异都不显示高亮效果。感谢大佬

**Comment by Shimada666** [comment]
不太清楚具体是什么需求，我理解是对 json 的某一个字段不进行 diff，但是我这不是 json 对比器..

**Comment by xiaowanghappyyyyyyyyyyyyyy** [comment]
对，传入的是通过JSON.stringify转化之后的数据，
![image](https://github.com/Shimada666/v-code-diff/assets/109127517/4d3e85eb-1f8b-485e-bfae-dc4ba98d0fb2)

**Comment by Shimada666** [comment]
> 对，传入的是通过JSON.stringify转化之后的数据， ![image](https://user-images.githubusercontent.com/109127517/264213392-4d3e85eb-1f8b-485e-bfae-dc4ba98d0fb2.png)

这功能恐怕不会支持。我们不是只做 json 对比展示，这功能并不通用

**Comment by xiaowanghappyyyyyyyyyyyyyy** [comment]
那能否请教一下，你是如何基于vue-code-diff进行封装的啊，我看了你的源码有点没有看懂，如果这个功能不支持的话，那我自己就基于vue-code-diff封装一个

**Comment by xiaowanghappyyyyyyyyyyyyyy** [comment]
看到你的v-code-diff源码中有使用vue-demi进行vue2和vue3代码兼容，也看到你写如何使用vue-demi的那篇文章，我这边主要就是只想实现上面说的功能就行，不需要兼容vue2和vue3，只在vue2项目中使用就行，但是我没有对现有插件进行扩展的经验，所以想请教一下思路，感谢感谢

**Comment by Shimada666** [comment]
一直没有基于 vue-code-diff 版本封装过，你说的可能是 diff2html。在 0.x 版本是在 vue-code-diff 的基础上进行了一些优化（底层是 diff2html 提供的 ui 绘制），适配了 vue2/vue3。现在是 1.x 版本，已经脱离了 diff2html，自己实现了 ui 绘制。
你要改的话，源码就是 src 下面的目录里的文件，改功能其实和兼容 vue2/3 没什么关系。你可能可以把它改成一个专门的 json 对比器，然后配置一些 prop 来支持你的黑名单

**Comment by xiaowanghappyyyyyyyyyyyyyy** [comment]
好的，了解了，我去试试，感谢

**Comment by Lruihao** [comment]
现在这个需求吗，应该是可以通过 ignoreMatchingLines 实现了：）
