### ISSUE TITLE
vue2.7版本 maxHeight 不生效问题

### ISSUE THREAD

**Issue by jingfeigithub** [Shimada666/v-code-diff#93]
CodeDiff文件里需要把
:style="{maxHeight}" 改为 :style="maxHeight"就可以了。
也可能是我不会用哈(非前端专业开发)

**Comment by Shimada666** [comment]
我试了下好像没有问题，比如
```vue
    <CodeDiff
      max-height="300px"
      :old-string="form.oldString"
      :new-string="form.newString"
      :language="form.language"
      :diff-style="form.diffStyle"
      output-format="side-by-side"
    />
```
你是怎么传的？

**Comment by jingfeigithub** [comment]
使用的插件是1.7.1版本，我的vue版本是vue2.7, max-height="300px"这样传项目编译不过了。

**Comment by jingfeigithub** [comment]
我用的是  :maxHeight 传的，应该是我用的不对

**Comment by jingfeigithub** [comment]
多谢了哈，我这实现了固定file-header的功能，滚动条滚动不会滑动了。是否考虑集成呢

**Comment by Shimada666** [comment]
> 多谢了哈，我这实现了固定file-header的功能，滚动条滚动不会滑动了。是否考虑集成呢

好啊，欢迎pr
